
-- races

CREATE TABLE races (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	code VARCHAR(20) NOT NULL,
	name VARCHAR(25) NOT NULL,
	UNIQUE (code)
);

	INSERT INTO races (id, code, name) VALUES
	(1, 'humans', 'Humains'),
	(2, 'nightelfs', 'Elfes de la nuit'),
	(3, 'orcs', 'Orcs'),
	(4, 'undeads', 'Morts vivants'),
	(5, 'neutrals', 'Neutres');

-- actions_types

CREATE TABLE actions_types (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	code VARCHAR(20) NOT NULL,
	name VARCHAR(25) NOT NULL,
	UNIQUE (code)
);

	INSERT INTO actions_types (id, code, name) VALUES
	(1, 'ready', 'Prêt !'),
	(2, 'warcry', 'Cri de guerre'),
	(3, 'what', 'What ?'),
	(4, 'yes', 'Oui ?'),
	(5, 'attack', 'Attaque'),
	(6, 'fun', 'Fun'),
	(7, 'death', 'Mort');

-- musics

CREATE TABLE musics (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	k_race INTEGER NOT NULL,
	code varchar(20) NOT NULL,
	name varchar(25) NOT NULL,
	file varchar(50) NOT NULL,
	UNIQUE (k_race, code),
	FOREIGN KEY (k_race) REFERENCES races (id) ON DELETE CASCADE ON UPDATE CASCADE
);

	INSERT INTO musics (k_race, code, name, file) VALUES

	-- humans

	(1, 'theme1', 'Thème 1', 'Human1.mp3'),
	(1, 'theme2', 'Thème 2', 'Human2.mp3'),
	(1, 'theme3', 'Thème 3', 'Human3.mp3'),
	(1, 'defeat', 'Défaite', 'HumanDefeat.mp3'),
	(1, 'victory', 'Victoire', 'HumanVictory.mp3'),

	-- nightelfs

	(2, 'theme1', 'Thème 1', 'NightElf1.mp3'),
	(2, 'theme2', 'Thème 2', 'NightElf2.mp3'),
	(2, 'theme3', 'Thème 3', 'NightElf3.mp3'),
	(2, 'defeat', 'Défaite', 'NightElfDefeat.mp3'),
	(2, 'victory', 'Victoire', 'NightElfVictory.mp3'),

	-- orcs

	(3, 'theme1', 'Thème 1', 'Orc1.mp3'),
	(3, 'theme2', 'Thème 2', 'Orc2.mp3'),
	(3, 'theme3', 'Thème 3', 'Orc3.mp3'),
	(3, 'defeat', 'Défaite', 'OrcDefeat.mp3'),
	(3, 'victory', 'Victoire', 'OrcVictory.mp3'),

	-- undeads

	(4, 'theme1', 'Thème 1', 'Undead1.mp3'),
	(4, 'theme2', 'Thème 2', 'Undead2.mp3'),
	(4, 'theme3', 'Thème 3', 'Undead3.mp3'),
	(4, 'defeat', 'Défaite', 'UndeadDefeat.mp3'),
	(4, 'victory', 'Victoire', 'UndeadVictory.mp3');

	-- neutrals

-- warnings

CREATE TABLE warnings (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	k_race INTEGER NOT NULL,
	code varchar(20) NOT NULL,
	name varchar(25) NOT NULL,
	file varchar(50) NOT NULL,
	UNIQUE (k_race, code),
	FOREIGN KEY (k_race) REFERENCES races (id) ON DELETE CASCADE ON UPDATE CASCADE
);

	INSERT INTO warnings (k_race, code, name, file) VALUES

	-- humans

	(1, 'allyattack', 'Notre allié est attaqué !', 'KnightAllyAttack1.wav'),
	(1, 'allyherodies', 'Le héros de notre allié est tombé', 'KnightAllyHeroDies1.wav'),
	(1, 'allytownattack', 'La ville de notre allié est assiégée', 'KnightAllyTownAttack1.wav'),
	(1, 'buildingcomplete', 'Travail terminé', 'PeasantBuildingComplete1.wav'),
	(1, 'cannotbuildthere', 'Je ne peux rien bâtir ici', 'PeasantCannotBuildThere1.wav'),
	(1, 'goldminecollapsed', 'Notre mine d''or s''est effondrée', 'KnightGoldMineCollapsed1.wav'),
	(1, 'goldminelow', 'Notre mine d''or est presque épuisée', 'KnightGoldMineLow1.wav'),
	(1, 'herodies', 'Notre héros est mort', 'KnightHeroDies1.wav'),
	(1, 'inventoryfull', 'Inventaire plein', 'KnightInventoryFull1.wav'),
	(1, 'noenergy', 'Mana insuffisant', 'KnightNoEnergy1.wav'),
	(1, 'nofood', 'Il faut plus de fermes', 'KnightNoFood1.wav'),
	(1, 'nogold', 'Nous avons besoin de plus d''or', 'KnightNoGold1.wav'),
	(1, 'nolumber', 'Il nous faut plus de bois', 'KnightNoLumber1.wav'),
	(1, 'researchcomplete', 'Recherche terminée', 'KnightResearchComplete1.wav'),
	(1, 'townattack', 'Notre ville est assiégée', 'KnightTownAttack1.wav'),
	(1, 'unitattack', 'Nous sommes attaqués', 'KnightUnitAttack1.wav'),
	(1, 'upgradecomplete', 'Amélioration terminée', 'KnightUpgradeComplete1.wav'),

	-- nightelfs

	(2, 'allyattack', 'Nous devons aider nos alliés !', 'SentinelAllyUnderAttack1.wav'),
	(2, 'allyherodies', 'Un champion allié est tombé !', 'SentinelAllyHeroDies1.wav'),
	(2, 'allytownattack', 'La ville de notre allié a besoin de nous !', 'SentinelAllyTownAttack1.wav'),
	(2, 'buildingcomplete', 'Bâtiment construit.', 'HuntressBuildingComplete1.wav'),
	(2, 'cannotbuildthere', 'Impossible de construire ici.', 'HuntressCannotBuildThere1.wav'),
	(2, 'goldminecollapsed', 'Notre mine d''or s''est effondrée', 'HuntressGoldMineCollapsed1.wav'),
	(2, 'goldminelow', 'Notre mine d''or est presque épuisée', 'HuntressGoldMineLow1.wav'),
	(2, 'herodies', 'Notre champion est mort', 'SentinelHeroDies1.wav'),
	(2, 'inventoryfull', 'Inventaire plein', 'SentinelInventoryFull1.wav'),
	(2, 'noenergy', 'Plus de mana', 'SentinelNoEnergy1.wav'),
	(2, 'nofood', 'Construisez plus de puits de lune', 'HuntressNoFood1.wav'),
	(2, 'nogold', 'Pas assez d''or', 'SentinelNoGold1.wav'),
	(2, 'nolumber', 'Pas assez de bois', 'SentinelNoLumber1.wav'),
	(2, 'researchcomplete', 'Recherche terminée', 'SentinelResearchComplete1.wav'),
	(2, 'townattack', 'Ils souillent notre sanctuaire !', 'SentinelTownAttack1.wav'),
	(2, 'unitattack', 'Nos guerriers engagent l''ennemi', 'SentinelUnitAttack1.wav'),
	(2, 'upgradecomplete', 'Amélioration terminée', 'SentinelUpgradeComplete1.wav'),

	-- orcs

	(3, 'allyattack', 'Notre allié a besoin de nous', 'GruntAllyUnderAttack1.wav'),
	(3, 'allyherodies', 'Le héros de notre allié est mort', 'GruntAllyHeroDies1.wav'),
	(3, 'allytownattack', 'La ville de notre allié est attaquée !', 'GruntAllyTownAttack1.wav'),
	(3, 'buildingcomplete', 'Travail terminé', 'PeonJobDone.wav'),
	(3, 'cannotbuildthere', 'Impossible de construire ici', 'PeonCannotBuildThere1.wav'),
	(3, 'goldminecollapsed', 'Notre mine d''or s''est effondrée', 'GruntGoldMineCollapsed1.wav'),
	(3, 'goldminelow', 'Notre mine d''or est presque épuisée', 'GruntGoldMineLow1.wav'),
	(3, 'herodies', 'Notre héros a été vaincu', 'GruntHeroDies1.wav'),
	(3, 'inventoryfull', 'Inventaire plein', 'GruntInventoryFull1.wav'),
	(3, 'noenergy', 'Pas assez de mana', 'GruntNoEnergy1.wav'),
	(3, 'nofood', 'Construisez d''autres antre des orcs', 'GruntNoFood1.wav'),
	(3, 'nogold', 'Il faut plus d''or', 'GruntNoGold1.wav'),
	(3, 'nolumber', 'Il faut plus de bois', 'GruntNoLumber1.wav'),
	(3, 'researchcomplete', 'Recherche terminée', 'GruntResearchComplete1.wav'),
	(3, 'townattack', 'Notre ville est attaquée !', 'GruntTownAttack1.wav'),
	(3, 'unitattack', 'Nous sommes attaqués !', 'GruntUnitAttack1.wav'),
	(3, 'upgradecomplete', 'Amélioration terminée', 'GruntUpgradeComplete1.wav'),

	-- undeads

	(4, 'allyattack', 'Nos frères ont besoin d''aide', 'NecromancerAllyUnderAttack1.wav'),
	(4, 'allyherodies', 'Un héros allié a succombé', 'NecromancerAllyHeroDies1.wav'),
	(4, 'allytownattack', 'La ville de nos frères est attaquée', 'NecromancerAllyTownAttack1.wav'),
	(4, 'buildingcomplete', 'L''invocation est accomplie', 'AcolyteBuildingComplete1.wav'),
	(4, 'cannotbuildthere', 'Je ne peux pas invoquer ici', 'AcolyteCannotBuildThere1.wav'),
	(4, 'goldminecollapsed', 'Notre mine d''or s''est effondrée', 'NecromancerGoldMineCollapsed1.wav'),
	(4, 'goldminelow', 'Notre mine d''or est presque vide', 'NecromancerGoldMineNearlyEmpty1.wav'),
	(4, 'herodies', 'Notre héros a succombé', 'NecromancerHeroDies1.wav'),
	(4, 'inventoryfull', 'Inventaire plein', 'NecromancerInventoryFull1.wav'),
	(4, 'noenergy', 'Pas assez de mana', 'NecromancerNoEnergy1.wav'),
	(4, 'nofood', 'Dressez plus de ziggourat', 'NecromancerNoFood1.wav'),
	(4, 'nogold', 'Il faut plus d''or', 'NecromancerNoGold1.wav'),
	(4, 'nolumber', 'Il faut plus de bois', 'NecromancerNoLumber1.wav'),
	(4, 'researchcomplete', 'Recherche terminée', 'NecromancerResearchComplete1.wav'),
	(4, 'townattack', 'Des infidèles attaquent notre ville !', 'NecromancerTownAttack1.wav'),
	(4, 'unitattack', 'Nos forces sont attaquées !', 'NecromancerUnitAttack1.wav'),
	(4, 'upgradecomplete', 'Amélioration terminée', 'NecromancerUpgradeComplete1.wav'),
	(4, 'placedoffblight', 'On ne peut invoquer que sur terre hantée', 'AcolytePlacedOffBlight1.wav'),

	-- neutrals

	(5, 'goldminecollapsed', 'Une mine d''or s''est effondrée', 'GenericWarningGoldCollapsed1.mp3'),
	(5, 'goldminelow', 'Une mine d''or est presque épuisée', 'GenericWarningGoldMineRunningLow1.mp3'),
	(5, 'herodies', 'Un héros est mort', 'GenericWarningHeroFallen1.mp3'),
	(5, 'noenergy', 'Pas assez de mana', 'GenericWarningNoMana1.mp3'),
	(5, 'researchcomplete', 'La recherche est terminée', 'GenericWarningResearchComplete1.mp3'),
	(5, 'townattack', 'Une ville est assiégée', 'GenericWarningTownAttack1.mp3'),
	(5, 'upgradecomplete', 'Amélioration terminée', 'GenericWarningUpgradeComplete1.mp3'),
	(5, 'unitattack', 'Les forces d''un joueur sont attaquées', 'GenericWarningUnitAttack1.mp3');

-- characters

CREATE TABLE characters (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	k_race INTEGER NOT NULL,
	code varchar(20) NOT NULL,
	name varchar(25) NOT NULL,
	tft tinyint(1) NOT NULL DEFAULT 0,
	UNIQUE (k_race, code),
	FOREIGN KEY (k_race) REFERENCES races (id) ON DELETE CASCADE ON UPDATE CASCADE
);

	INSERT INTO characters (id, k_race, code, name, tft) VALUES

	-- humans

	(1, 1, 'paladin', 'Paladin', 0),
	(2, 1, 'mountainking', 'Roi de la montagne', 0),
	(3, 1, 'archmage', 'Archimage', 0),
	(4, 1, 'bloodelfmage', 'Mage elfe de sang', 1),
	(5, 1, 'peasant', 'Paysan', 0),
	(6, 1, 'footman', 'Soldat', 0),
	(7, 1, 'rifleman', 'Fusiller', 0),
	(8, 1, 'knight', 'Chevalier', 0),
	(9, 1, 'gyrocopter', 'Gyrocoptère', 0),
	(10, 1, 'gryphonrider', 'Chevaucheur de gryphon', 0),
	(11, 1, 'priest', 'Prêtre', 0),
	(12, 1, 'sorceress', 'Sorcière', 0),
	(13, 1, 'spellbreaker', 'spellbreaker', 1),
	(14, 1, 'hawkrider', 'hawkrider', 1),
	(59, 1, 'jaina', 'Jaina', 0),
	(60, 1, 'mortarteam', 'Mortier', 0),
	(61, 1, 'muradin', 'Muradin', 0),
	(62, 1, 'uther', 'Uther', 0),
	(63, 1, 'windserpent', 'windserpent', 0),
	(64, 1, 'villager', 'Villageois', 0),
	(65, 1, 'captain', 'Capitaine', 0),

	-- nightelfs

	(28, 2, 'demonhunter', 'Chasseur de démons', 0),
	(100, 2, 'morpheddemonhunter', 'Chasseur de démons transformé', 0),
	(29, 2, 'keeperofthegrove', 'keeperofthegrove', 0),
	(30, 2, 'moonpriestess', 'Prêtresse de la lune', 0),
	(31, 2, 'warden', 'warden', 1),
	(32, 2, 'archer', 'Archer', 0),
	(33, 2, 'huntress', 'Chasseresse', 0),
	(34, 2, 'dryad', 'Dryade', 0),
	(35, 2, 'druidoftheclaw', 'druidoftheclaw', 0),
	(36, 2, 'druidofthetalon', 'druidofthetalon', 0),
	(37, 2, 'hippogryphrider', 'Chevaucheur d''hippogryphe', 0),
	(73, 2, 'furion', 'Furion', 0),
	(74, 2, 'illidan', 'Illidan', 0),
	(75, 2, 'illidanmorphed', 'Illidan transformé', 0),
	(76, 2, 'shandris', 'Shandris', 0),
	(77, 2, 'sylvanas', 'Sylvanas', 0),
	(78, 2, 'tyrande', 'Tyrande', 0),

	-- orcs

	(15, 3, 'blademaster', 'blademaster', 0),
	(16, 3, 'farseer', 'farseer', 0),
	(17, 3, 'taurenchieftain', 'taurenchieftain', 0),
	(18, 3, 'shadowhunter', 'shadowhunter', 1),
	(19, 3, 'peon', 'peon', 0),
	(20, 3, 'grunt', 'grunt', 0),
	(21, 3, 'headhunter', 'headhunter', 0),
	(22, 3, 'wolfrider', 'wolfrider', 0),
	(23, 3, 'wyvernrider', 'wyvernrider', 0),
	(24, 3, 'tauren', 'tauren', 0),
	(25, 3, 'shaman', 'shaman', 0),
	(26, 3, 'witchdoctor', 'witchdoctor', 0),
	(27, 3, 'spiritwalker', 'spiritwalker', 1),
	(79, 3, 'cairne', 'Cairne', 0),
	(80, 3, 'grom', 'Grom', 0),
	(81, 3, 'thrall', 'Thrall', 0),
	(82, 3, 'warlord', 'Warlord', 0),

	-- undeads

	(38, 4, 'deathknight', 'Chevalier de la mort', 0),
	(39, 4, 'lich', 'Liche', 0),
	(40, 4, 'dreadlord', 'dreadlord', 0),
	(41, 4, 'cryptlord', 'cryptlord', 1),
	(42, 4, 'acolyte', 'Acolyte', 0),
	(43, 4, 'ghoul', 'Goule', 0),
	(44, 4, 'cryptfiend', 'cryptfiend', 0),
	(45, 4, 'abomination', 'Abomination', 0),
	(46, 4, 'necromancer', 'Nécromancien', 0),
	(47, 4, 'banshee', 'Banshee', 0),
	(48, 4, 'shade', 'Ombre', 0),
	(57, 4, 'arthas', 'Arthas', 0),
	(83, 4, 'kelthuzad', 'Kelthuzad', 0),
	(85, 4, 'tichondrius', 'Tichondrius', 0),

	-- neutrals

	(49, 5, 'alchemist', 'alchemist', 1),
	(50, 5, 'ladyvash', 'ladyvash', 1),
	(51, 5, 'tinker', 'tinker', 1),
	(52, 5, 'beastmaster', 'beastmaster', 1),
	(53, 5, 'pandaren', 'pandaren', 1),
	(54, 5, 'darkranger', 'darkranger', 1),
	(55, 5, 'pitlord', 'pitlord', 0),
	(56, 5, 'firelord', 'firelord', 1),

	(58, 5, 'bandit', 'Bandit', 0),
	(66, 5, 'foresttroll', 'foresttroll', 0),
	(67, 5, 'goblinmerchant', 'goblinmerchant', 0),
	(68, 5, 'goblinsapper', 'goblinsapper', 0),
	(69, 5, 'goblinzeppelin', 'goblinzeppelin', 0),
	(70, 5, 'icetroll', 'icetroll', 0),
	(71, 5, 'ogre', 'ogre', 0),
	(72, 5, 'satyre', 'satyre', 0);

-- actions

CREATE TABLE actions (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	k_character INTEGER NOT NULL,
	k_action_type INTEGER NOT NULL,
	code varchar(20) NOT NULL,
	name varchar(25) NOT NULL,
	file varchar(50) NOT NULL,
	FOREIGN KEY (k_character) REFERENCES characters (id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (k_action_type) REFERENCES actions_types (id) ON DELETE CASCADE ON UPDATE CASCADE
);

	INSERT INTO actions (k_character, k_action_type, code, name, file) VALUES

	-- humans

	(1, 1, 'ready1', 'Ma foi est mon glaive', 'HeroPaladinReady1.wav'),
	(1, 2, 'warcry1', 'Que lightbringer te montre la voie', 'HeroPaladinWarcry1.wav'),
	(1, 3, 'what1', 'Qu''attendez-vous de moi ?', 'HeroPaladinWhat1.wav'),
	(1, 3, 'what2', 'Je n''ai aucune crainte', 'HeroPaladinWhat2.wav'),
	(1, 3, 'what3', 'J''affronterai tous les périls', 'HeroPaladinWhat3.wav'),
	(1, 3, 'what4', 'Comme il vous siéra', 'HeroPaladinWhat4.wav'),
	(1, 4, 'yes1', 'Comme vous le souhaitez', 'HeroPaladinYes1.wav'),
	(1, 4, 'yes2', 'Pour l''honneur', 'HeroPaladinYes2.wav'),
	(1, 4, 'yes3', 'Pour la foi', 'HeroPaladinYes3.wav'),
	(1, 4, 'yes4', 'Il en sera ainsi', 'HeroPaladinYes4.wav'),
	(1, 5, 'attack1', 'Je suis le bras de la justice', 'HeroPaladinYesAttack1.wav'),
	(1, 5, 'attack3', 'Mort aux infidèles', 'HeroPaladinYesAttack3.wav'),
	(1, 5, 'attack2', 'En votre nom', 'HeroPaladinYesAttack2.wav'),
	(1, 6, 'fun1', 'Je sers la foi', 'HeroPaladinPissed1.wav'),
	(1, 6, 'fun2', 'Je suis le bouclier des croyants', 'HeroPaladinPissed2.wav'),
	(1, 6, 'fun3', 'Bas les pattes ! J''ai fait voeux de chasteté.', 'HeroPaladinPissed3.wav'),
	(1, 6, 'fun4', 'Oui JP, c''est mon dernier mot', 'HeroPaladinPissed4.wav'),
	(1, 6, 'fun5', 'Je vais faire appel au public', 'HeroPaladinPissed5.wav'),
	(1, 6, 'fun6', 'Le coté obscur n''est pas le plus fort, non. Plus rapide ! Plus facile. Plus séduisant...', 'HeroPaladinPissed6.wav'),
	(1, 7, 'death1', 'Mort', 'HeroPaladinDeath.wav'),

	(2, 1, 'ready1', 'Prêt !', 'HeroMountainKingReady1.wav'),
	(2, 2, 'warcry1', 'Pour Khaz Modan !', 'HeroMountainKingWarcry1.wav'),
	(2, 3, 'what1', 'Oui ?', 'HeroMountainKingWhat1.wav'),
	(2, 3, 'what2', 'Vivement un peu d''action', 'HeroMountainKingWhat2.wav'),
	(2, 3, 'what3', 'J''attend les ordres !', 'HeroMountainKingWhat3.wav'),
	(2, 3, 'what4', 'Mmm ?', 'HeroMountainKingWhat4.wav'),
	(2, 4, 'yes1', 'Très bien !', 'HeroMountainKingYes1.wav'),
	(2, 4, 'yes2', 'C''est parti !', 'HeroMountainKingYes2.wav'),
	(2, 4, 'yes3', 'En route !', 'HeroMountainKingYes3.wav'),
	(2, 4, 'yes4', 'Laissez-moi passer !', 'HeroMountainKingYes4.wav'),
	(2, 5, 'attack1', 'Aux armes !', 'HeroMountainKingYesAttack1.wav'),
	(2, 5, 'attack2', 'Ca va faire mal', 'HeroMountainKingYesAttack2.wav'),
	(2, 5, 'attack3', 'Tranche, taille et cours !', 'HeroMountainKingYesAttack3.wav'),
	(2, 5, 'attack4', 'A l''assaut !', 'HeroMountainKingYesAttack4.wav'),
	(2, 6, 'fun1', 'Un pastis, sinon rien', 'HeroMountainKingPissed1.wav'),
	(2, 6, 'fun2', 'Tavernier, à boire et à manger', 'HeroMountainKingPissed2.wav'),
	(2, 6, 'fun3', 'Qui est gros ?', 'HeroMountainKingPissed3.wav'),
	(2, 6, 'fun4', 'Petit mais costaud !', 'HeroMountainKingPissed4.wav'),
	(2, 6, 'fun5', 'On pourrait pas en discuter autour d''une chopine ?', 'HeroMountainKingPissed5.wav'),
	(2, 6, 'fun6', 'Un tonneau d''hydromel, ça use le gosier', 'HeroMountainKingPissed6.wav'),
	(2, 6, 'fun7', 'Du rhum, des femmes, et d''la bière nom de Dieu !', 'HeroMountainKingPissed7.wav'),
	(2, 7, 'death1', 'Mort', 'HeroMountainKingDeath.wav'),

	(3, 1, 'ready1', 'J''espère pour vous que ça en vaut la peine', 'HeroArchmageReady1.wav'),
	(3, 2, 'warcry1', 'Pour la gloire', 'HeroArchmageWarcry1.wav'),
	(3, 3, 'what1', 'Ainsi vous réclamez mon aide', 'HeroArchmageWhat1.wav'),
	(3, 3, 'what2', 'Qui a-t-il, encore ?', 'HeroArchmageWhat2.wav'),
	(3, 3, 'what3', 'Je vous écoute', 'HeroArchmageWhat3.wav'),
	(3, 3, 'what4', 'Alors ?', 'HeroArchmageWhat4.wav'),
	(3, 4, 'yes1', 'J''ai hâte d''y être', 'HeroArchmageYes1.wav'),
	(3, 4, 'yes2', 'Parfait !', 'HeroArchmageYes2.wav'),
	(3, 4, 'yes3', 'Puisqu''il le faut', 'HeroArchmageYes3.wav'),
	(3, 4, 'yes4', 'Fort bien', 'HeroArchmageYes4.wav'),
	(3, 5, 'attack1', 'J''engage le combat', 'HeroArchmageYes1.wav'),
	(3, 5, 'attack2', 'Pour la gloire', 'HeroArchmageYes2.wav'),
	(3, 5, 'attack3', 'Nim flori...', 'HeroArchmageYes3.wav'),
	(3, 6, 'fun1', 'La seule chance qu''on a de gagner la guerre, c''est qu''en face ils soient aussi cons qu''ici.', 'HeroArchmagePissed1.wav'),
	(3, 6, 'fun2', 'Vous avez lu Clausewitz ?', 'HeroArchmagePissed2.wav'),
	(3, 6, 'fun3', 'Et Sun-Tzu vous l''avez lu ?', 'HeroArchmagePissed3.wav'),
	(3, 6, 'fun4', 'Magie, magie, et vos idées n''ont pas de génie', 'HeroArchmagePissed4.wav'),
	(3, 7, 'death1', 'Mort', 'HeroArchmageDeath.wav'),

	(5, 1, 'ready1', 'Prêt à travailler !', 'PeasantReady1.wav'),
	(5, 2, 'warcry1', 'Haaaaaa', 'PeasantWarcry1.wav'),
	(5, 3, 'what1', 'Oui messire ?', 'PeasantWhat1.wav'),
	(5, 3, 'what2', 'Qu''y a-t-il ?', 'PeasantWhat2.wav'),
	(5, 3, 'what3', 'Encore du travail ?', 'PeasantWhat3.wav'),
	(5, 3, 'what4', 'Pardon ?', 'PeasantWhat4.wav'),
	(5, 4, 'yes1', 'Bien', 'PeasantYes1.wav'),
	(5, 4, 'yes2', 'Oui monseigneur', 'PeasantYes2.wav'),
	(5, 4, 'yes3', 'Très bien', 'PeasantYes3.wav'),
	(5, 4, 'yes4', 'Je m''en charge', 'PeasantYes4.wav'),
	(5, 5, 'attack1', 'Je peux essayer', 'PeasantYesAttack1.wav'),
	(5, 5, 'attack2', 'Si vous le voulez vraiment', 'PeasantYesAttack2.wav'),
	(5, 5, 'attack3', 'Vous n''avez personne d''autre ?', 'PeasantYesAttack3.wav'),
	(5, 5, 'attack4', 'Ça y est, je suis mort...', 'PeasantYesAttack4.wav'),
	(5, 6, 'fun1', 'Votre prénom, c''est François, c''est juste ?', 'PeasantPissed1.wav'),
	(5, 6, 'fun2', 'Il est bon ! C''est un champion du monde !', 'PeasantPissed2.wav'),
	(5, 6, 'fun3', 'Il pourrait me faire l''historique de la louche à travers les âges ?', 'PeasantPissed3.wav'),
	(5, 6, 'fun4', 'Ne m''invitez jamais à diner, j''aurais toujours un doute.', 'PeasantPissed4.wav'),
	(5, 6, 'fun5', 'il essaie de faire de l''humour ! Ecoutez ça, c''est pathétique.', 'PeasantPissed5.wav'),
	(5, 7, 'death1', 'Mort', 'PeasantDeath.wav'),

	(6, 1, 'ready1', 'Prêt à l''action', 'FootmanReady1.wav'),
	(6, 2, 'warcry1', 'Pour Lordaeron !', 'FootmanWarcry1.wav'),
	(6, 3, 'what1', 'Quels sont les ordres ?', 'FootmanWhat1.wav'),
	(6, 3, 'what2', 'Que voulez-vous ?', 'FootmanWhat2.wav'),
	(6, 3, 'what3', 'Oui monseigneur ?', 'FootmanWhat3.wav'),
	(6, 3, 'what4', 'Donnez vos ordres !', 'FootmanWhat4.wav'),
	(6, 4, 'yes1', 'Compris, monseigneur', 'FootmanYes1.wav'),
	(6, 4, 'yes3', 'A vos ordres !', 'FootmanYes3.wav'),
	(6, 4, 'yes2', 'J''y vais !', 'FootmanYes2.wav'),
	(6, 4, 'yes4', 'Certainement !', 'FootmanYes4.wav'),
	(6, 5, 'attack1', 'Laissez-les moi !', 'FootmanYesAttack1.wav'),
	(6, 5, 'attack2', 'A l''attaque !', 'FootmanYesAttack2.wav'),
	(6, 5, 'attack3', 'Aux armes !', 'FootmanYesAttack3.wav'),
	(6, 6, 'fun1', 'Sortez couverts !', 'FootmanPissed1.wav'),
	(6, 6, 'fun2', 'Avant l''heure c''est pas l''heure, après l''heure c''est plus l''heure.', 'FootmanPissed2.wav'),
	(6, 6, 'fun3', 'Engagez-vous, rengagez-vous, qu''il disait Lothar.', 'FootmanPissed3.wav'),
	(6, 6, 'fun4', 'Ce n''est qu''une égratignure', 'FootmanPissed4.wav'),
	(6, 7, 'death1', 'Mort', 'FootmanDeath.wav'),

	(7, 1, 'ready1', 'Armé, et paré !', 'RiflemanReady1.wav'),
	(7, 2, 'warcry1', 'Pour Ironforge !', 'RiflemanWarcry1.wav'),
	(7, 3, 'what1', 'Oui chef !', 'RiflemanWhat1.wav'),
	(7, 3, 'what2', 'Ma cible ?', 'RiflemanWhat2.wav'),
	(7, 3, 'what3', 'Quelle est ma cible ?', 'RiflemanWhat3.wav'),
	(7, 3, 'what4', 'Que voulez-vous ?', 'RiflemanWhat4.wav'),
	(7, 4, 'yes1', 'Ooookay !', 'RiflemanYes1.wav'),
	(7, 4, 'yes2', 'J''m''en occupe !', 'RiflemanYes2.wav'),
	(7, 4, 'yes3', 'C''est parti !', 'RiflemanYes3.wav'),
	(7, 4, 'yes4', 'Oui ?', 'RiflemanYes4.wav'),
	(7, 5, 'attack1', 'Feu !', 'RiflemanYesAttack1.wav'),
	(7, 5, 'attack2', 'J''ai ma cible en mire !', 'RiflemanYesAttack2.wav'),
	(7, 5, 'attack3', 'Et un pruneau bien chaud, un !', 'RiflemanYesAttack3.wav'),
	(7, 5, 'attack4', 'Tirez, pour tuer !', 'RiflemanYesAttack4.wav'),
	(7, 6, 'fun1', 'Dans ce monde, y''a deux types d''hommes : ceux qui sont armés, et ceux qui creusent.', 'RiflemanPissed1.wav'),
	(7, 6, 'fun2', 'Toi, tu creuse', 'RiflemanPissed2.wav'),
	(7, 6, 'fun3', 'Peut importe ou, quand et comment, mais quelqu''un doit payer', 'RiflemanPissed3.wav'),
	(7, 6, 'fun4', 'Adrienne !!', 'RiflemanPissed4.wav'),
	(7, 6, 'fun5', 'Tu réfléchira avant de tout engluer un mec qui a un positroneur désintégrant. Hein ?', 'RiflemanPissed5.wav'),
	(7, 6, 'fun6', 'Raccourci ton rayon', 'RiflemanPissed6.wav'),
	(7, 6, 'fun7', 'Il faut pas croiser les effluves, c''est mal', 'RiflemanPissed7.wav'),
	(7, 6, 'fun8', 'Partenaire particulier, cherche partenaire particulière', 'RiflemanPissed8.wav'),
	(7, 7, 'death1', 'Mort', 'RiflemanDeath.wav'),

	(8, 1, 'ready1', 'J''attend vos ordres', 'KnightReady1.wav'),
	(8, 2, 'warcry1', 'Pour l''honneur, et la liberté !', 'KnightWarcry1.wav'),
	(8, 3, 'what1', 'Sir ?', 'KnightWhat1.wav'),
	(8, 3, 'what2', 'Votre honneur ?', 'KnightWhat2.wav'),
	(8, 3, 'what3', 'Quels sont vos ordres ?', 'KnightWhat3.wav'),
	(8, 3, 'what4', 'Oui, monseigneur ?', 'KnightWhat4.wav'),
	(8, 4, 'yes1', 'Sur le champ !', 'KnightYes1.wav'),
	(8, 4, 'yes2', 'Pour le roi !', 'KnightYes2.wav'),
	(8, 4, 'yes3', 'Certainement', 'KnightYes3.wav'),
	(8, 4, 'yes4', 'Je m''en charge', 'KnightYes4.wav'),
	(8, 5, 'attack1', 'Pour le roi !', 'KnightYesAttack1.wav'),
	(8, 5, 'attack2', 'Je vais le pourfendre !', 'KnightYesAttack2.wav'),
	(8, 5, 'attack3', 'Jusqu''à la mort !', 'KnightYesAttack3.wav'),
	(8, 6, 'fun1', 'Je suis l''homme qui tombe à pic', 'KnightPissed1.wav'),
	(8, 6, 'fun2', 'Par le pouvoir du crâne ancestral !', 'KnightPissed2.wav'),
	(8, 6, 'fun3', 'Ils sont fous, ces romains', 'KnightPissed3.wav'),
	(8, 6, 'fun4', 'Les chaussettes de l''archiduchesse, sont-elles sêches, archi-sêches ?', 'KnightPissed4.wav'),
	(8, 6, 'fun5', 'Je n''ai pas dit "ni"', 'KnightPissed5.wav'),
	(8, 6, 'fun6', 'Un chasseur sachant chasser sans son chien est un bon chasseur.', 'KnightPissed6.wav'),
	(8, 7, 'death1', 'Mort', 'KnightDeath.wav'),

	(9, 1, 'ready1', 'Larguez les amarres', 'GyrocopterReady1.wav'),
	(9, 2, 'warcry1', 'Vers l''infini, et au-delà !', 'GyrocopterWarcry1.wav'),
	(9, 3, 'what1', 'Que puis-je pour vous ?', 'GyrocopterWhat1.wav'),
	(9, 3, 'what2', 'Quel est le plan de vol ?', 'GyrocopterWhat2.wav'),
	(9, 3, 'what3', 'Donnez-moi le cap', 'GyrocopterWhat3.wav'),
	(9, 3, 'what4', 'Tous les systèmes, OK !', 'GyrocopterWhat4.wav'),
	(9, 3, 'what5', 'Ah ! Encore vous ?', 'GyrocopterWhat5.wav'),
	(9, 4, 'yes1', 'Roger', 'GyrocopterYes1.wav'),
	(9, 4, 'yes2', 'Cap enregistré', 'GyrocopterYes2.wav'),
	(9, 4, 'yes3', 'On approche du mur du son', 'GyrocopterYes3.wav'),
	(9, 4, 'yes4', 'Quoi, là-bas ?', 'GyrocopterYes4.wav'),
	(9, 4, 'yes5', 'Ils ne m''entendront pas venir !', 'GyrocopterYes5.wav'),
	(9, 5, 'attack1', 'Bombe, larguée', 'GyrocopterYesAttack1.wav'),
	(9, 5, 'attack2', 'Cible verrouillée', 'GyrocopterYesAttack2.wav'),
	(9, 5, 'attack3', 'J''attaque la cible !', 'GyrocopterYesAttack3.wav'),
	(9, 5, 'attack4', 'Ça va faire mal !', 'GyrocopterYesAttack4.wav'),
	(9, 6, 'fun1', 'Rogue Leader, au rapport', 'GyrocopterPissed1.wav'),
	(9, 6, 'fun2', 'Restez en ligne', 'GyrocopterPissed2.wav'),
	(9, 6, 'fun3', 'Je ne peux pas, ça bouge trop', 'GyrocopterPissed3.wav'),
	(9, 6, 'fun4', 'Il est dans la ventilation', 'GyrocopterPissed4.wav'),
	(9, 6, 'fun5', 'S''il peut saigner, on peut le tuer', 'GyrocopterPissed5.wav'),
	(9, 6, 'fun6', 'Je parle d''une certaine spiritualité, elle est faite de oui, de non', 'GyrocopterPissed6.wav'),
	(9, 6, 'fun7', 'Y''a-t-il un pilote dans l''avion ?', 'GyrocopterPissed7.wav'),
	(9, 6, 'fun8', 'Ils ne sont pas à l''attention de savoir qu''ils existent', 'GyrocopterPissed8.wav'),
	(9, 7, 'death1', 'Mort', 'GyrocopterDeath1.wav'),

	(10, 1, 'ready1', 'Je vis pour servir', 'GryphonRiderReady1.wav'),
	(10, 2, 'warcry1', 'Pour Khaz Modan !', 'GryphonRiderWarcry1.wav'),
	(10, 3, 'what1', 'Ma vie est entre vos mains', 'GryphonRiderWhat1.wav'),
	(10, 3, 'what2', 'Oui, chef ?', 'GryphonRiderWhat2.wav'),
	(10, 3, 'what3', 'Je suis votre nain', 'GryphonRiderWhat3.wav'),
	(10, 3, 'what4', 'La fin justifie les moyens', 'GryphonRiderWhat4.wav'),
	(10, 3, 'what5', '', 'GryphonRiderWhat5.wav'),
	(10, 4, 'yes1', 'Yep, comptez sur moi', 'GryphonRiderYes1.wav'),
	(10, 4, 'yes2', 'C''est vous le patron !', 'GryphonRiderYes2.wav'),
	(10, 4, 'yes3', 'Pas de problème !', 'GryphonRiderYes3.wav'),
	(10, 4, 'yes4', 'Super', 'GryphonRiderYes4.wav'),
	(10, 4, 'yes5', 'Vers les cieux !', 'GryphonRiderYes5.wav'),
	(10, 5, 'attack1', 'La mort vient du ciel !', 'GryphonRiderYesAttack1.wav'),
	(10, 5, 'attack2', 'Vers la victoire !', 'GryphonRiderYesAttack2.wav'),
	(10, 5, 'attack3', 'Par la barbe de Muradin !', 'GryphonRiderYesAttack3.wav'),
	(10, 6, 'fun1', 'Boire ou conduire, il faut choisir', 'GryphonRiderPissed1.wav'),
	(10, 6, 'fun2', 'C''est pas la taille qui compte, c''est le tranchant', 'GryphonRiderPissed2.wav'),
	(10, 6, 'fun3', 'Un p''tit clou ?', 'GryphonRiderPissed3.wav'),
	(10, 6, 'fun4', 'Que la force soit avec toi, Luke.', 'GryphonRiderPissed4.wav'),
	(10, 6, 'fun5', 'Un cavalier, qui surgit hors de la nuit... Part, à l''aventure au galop...', 'GryphonRiderPissed5.wav'),
	(10, 7, 'death1', 'Mort', 'GryphonRiderDeath1.wav'),

	(11, 1, 'ready1', 'Je viens purifier cette contrée', 'PriestReady1.wav'),
	(11, 2, 'warcry1', 'Frappez-les tous !', 'PriestWarcry1.wav'),
	(11, 3, 'what1', 'Quels sont vos maux ?', 'PriestWhat1.wav'),
	(11, 3, 'what2', 'Oui, mon fils ?', 'PriestWhat2.wav'),
	(11, 3, 'what3', 'Souhaitez-vous ma bénédiction ?', 'PriestWhat3.wav'),
	(11, 3, 'what4', 'Y''a-t-il des blessés ?', 'PriestWhat4.wav'),
	(11, 4, 'yes1', 'Je suis votre serviteur', 'PriestYes1.wav'),
	(11, 4, 'yes2', 'Bien entendu', 'PriestYes2.wav'),
	(11, 4, 'yes3', 'Comme il vous plaira', 'PriestYes3.wav'),
	(11, 4, 'yes4', 'Sur le champ', 'PriestYes4.wav'),
	(11, 5, 'attack1', 'Notre malédiction vous barrera la route', 'PriestYesAttack1.wav'),
	(11, 6, 'fun1', 'Y''a pas deux félés dans Warcraft 3', 'PriestPissed1.wav'),
	(11, 6, 'fun2', 'On se lève tous pour la Lumière', 'PriestPissed2.wav'),
	(11, 6, 'fun3', 'Quand 900 ans comme moi tu aura, moins en forme tu sera', 'PriestPissed3.wav'),
	(11, 6, 'fun4', 'Au secours ! Il y a un peck qui me menace, il a un gland dans la main', 'PriestPissed4.wav'),
	(11, 6, 'fun5', 'Mais moi les dingues, j''les soigne', 'PriestPissed5.wav'),
	(11, 6, 'fun6', 'Aux quatre coins de Paris on va le retrouver éparpillé par petits bouts façon puzzle', 'PriestPissed6.wav'),
	(11, 7, 'death1', 'Mort', 'PriestDeath.wav'),

	(12, 1, 'ready1', '1', 'SorceressReady1.wav'),
	(12, 2, 'warcry1', '1', 'SorceressWarcry1.wav'),
	(12, 3, 'what1', '1', 'SorceressWhat1.wav'),
	(12, 3, 'what2', '2', 'SorceressWhat2.wav'),
	(12, 3, 'what3', '3', 'SorceressWhat3.wav'),
	(12, 3, 'what4', '4', 'SorceressWhat4.wav'),
	(12, 3, 'what5', '5', 'SorceressWhat5.wav'),
	(12, 4, 'yes1', '1', 'SorceressYes1.wav'),
	(12, 4, 'yes2', '2', 'SorceressYes2.wav'),
	(12, 4, 'yes3', '3', 'SorceressYes3.wav'),
	(12, 4, 'yes4', '4', 'SorceressYes4.wav'),
	(12, 5, 'attack1', '1', 'SorceressYesAttack1.wav'),
	(12, 5, 'attack2', '2', 'SorceressYesAttack2.wav'),
	(12, 5, 'attack3', '3', 'SorceressYesAttack3.wav'),
	(12, 6, 'fun1', '1', 'SorceressPissed1.wav'),
	(12, 6, 'fun2', '2', 'SorceressPissed2.wav'),
	(12, 6, 'fun3', '3', 'SorceressPissed3.wav'),
	(12, 6, 'fun4', '4', 'SorceressPissed4.wav'),
	(12, 6, 'fun5', '5', 'SorceressPissed5.wav'),
	(12, 6, 'fun6', '6', 'SorceressPissed6.wav'),
	(12, 7, 'death1', 'Mort', 'SorceressDeath.wav'),

	(59, 2, 'warcry1', 'Pour Dalaran !', 'JainaWarcry1.wav'),
	(59, 3, 'what1', 'Je peux aider ?', 'JainaWhat1.wav'),
	(59, 3, 'what2', 'C''est étrange', 'JainaWhat2.wav'),
	(59, 3, 'what3', 'Chut ! J''essaie de réfléchir !', 'JainaWhat3.wav'),
	(59, 3, 'what4', 'Quel est votre plan ?', 'JainaWhat4.wav'),
	(59, 4, 'yes1', 'Ça m''a l''air bien', 'JainaYes1.wav'),
	(59, 4, 'yes2', 'Je vais voir', 'JainaYes2.wav'),
	(59, 4, 'yes3', 'Ça parait intéressant', 'JainaYes3.wav'),
	(59, 4, 'yes4', 'Je m''en charge', 'JainaYes4.wav'),
	(59, 5, 'attack1', 'Je déteste avoir recours à la violence', 'JainaYesAttack1.wav'),
	(59, 5, 'attack2', 'Vous l''avez cherché !', 'JainaYesAttack2.wav'),
	(59, 6, 'fun1', 'Je ne suis pas un guerrier', 'JainaPissed1.wav'),
	(59, 6, 'fun2', 'Je voulais étudier paisiblement !', 'JainaPissed2.wav'),
	(59, 6, 'fun3', 'Il y a un grand trouble dans les courants magiques', 'JainaPissed3.wav'),
	(59, 6, 'fun4', 'Je prie que mon père soit sain et sauf', 'JainaPissed4.wav'),
	(59, 6, 'fun5', 'Les évènements commencent à être un peu bizarres', 'JainaPissed5.wav'),

	(60, 1, 'ready1', '1', 'MortarteamReady1.wav'),
	(60, 2, 'warcry1', '1', 'MortarteamWarcry1.wav'),
	(60, 3, 'what1', '1', 'MortarteamWhat1.wav'),
	(60, 3, 'what2', '2', 'MortarteamWhat2.wav'),
	(60, 3, 'what3', '3', 'MortarteamWhat3.wav'),
	(60, 3, 'what4', '4', 'MortarteamWhat4.wav'),
	(60, 4, 'yes1', '1', 'MortarteamYes1.wav'),
	(60, 4, 'yes2', '2', 'MortarteamYes2.wav'),
	(60, 4, 'yes3', '3', 'MortarteamYes3.wav'),
	(60, 4, 'yes4', '4', 'MortarteamYes4.wav'),
	(60, 4, 'yes5', '5', 'MortarteamYes5.wav'),
	(60, 4, 'yes6', '6', 'MortarteamYes6.wav'),
	(60, 5, 'attack1', '1', 'MortarteamYesAttack1.wav'),
	(60, 5, 'attack2', '2', 'MortarteamYesAttack2.wav'),
	(60, 5, 'attack3', '3', 'MortarteamYesAttack3.wav'),
	(60, 5, 'attack4', '4', 'MortarteamYesAttack4.wav'),
	(60, 5, 'attack5', '5', 'MortarteamYesAttack5.wav'),
	(60, 6, 'fun1', '1', 'MortarteamPissed1.wav'),
	(60, 6, 'fun2', '2', 'MortarteamPissed2.wav'),
	(60, 6, 'fun3', '3', 'MortarteamPissed3.wav'),
	(60, 6, 'fun4', '4', 'MortarteamPissed4.wav'),
	(60, 6, 'fun5', '5', 'MortarteamPissed5.wav'),
	(60, 6, 'fun6', '6', 'MortarteamPissed6.wav'),
	(60, 6, 'fun7', '7', 'MortarteamPissed7.wav'),
	(60, 6, 'fun8', '8', 'MortarteamPissed8.wav'),
	(60, 6, 'fun9', '9', 'MortarteamPissed9.wav'),
	(60, 7, 'death1', '1', 'MortarteamDeath.wav'),
	(60, 7, 'deathexplode', 'e', 'MortarteamDeathexplode.wav'),

	(61, 2, 'warcry1', '1', 'MuradinWarcry1.wav'),
	(61, 3, 'what1', '1', 'MuradinWhat1.wav'),
	(61, 3, 'what2', '2', 'MuradinWhat2.wav'),
	(61, 3, 'what3', '3', 'MuradinWhat3.wav'),
	(61, 3, 'what4', '4', 'MuradinWhat4.wav'),
	(61, 4, 'yes1', '1', 'MuradinYes1.wav'),
	(61, 4, 'yes2', '2', 'MuradinYes2.wav'),
	(61, 4, 'yes3', '3', 'MuradinYes3.wav'),
	(61, 4, 'yes4', '4', 'MuradinYes4.wav'),
	(61, 5, 'attack1', '1', 'MuradinYesAttack1.wav'),
	(61, 5, 'attack2', '2', 'MuradinYesAttack2.wav'),
	(61, 5, 'attack3', '3', 'MuradinYesAttack3.wav'),
	(61, 6, 'fun1', '1', 'MuradinPissed1.wav'),
	(61, 6, 'fun2', '2', 'MuradinPissed2.wav'),
	(61, 6, 'fun3', '3', 'MuradinPissed3.wav'),
	(61, 6, 'fun4', '4', 'MuradinPissed4.wav'),
	(61, 6, 'fun5', '5', 'MuradinPissed5.wav'),
	(61, 6, 'fun6', '6', 'MuradinPissed6.wav'),
	(61, 6, 'fun7', '7', 'MuradinPissed7.wav'),
	(61, 6, 'fun8', '8', 'MuradinPissed8.wav'),

	(62, 2, 'warcry1', '1', 'UtherWarcry1.wav'),
	(62, 3, 'what1', '1', 'UtherWhat1.wav'),
	(62, 3, 'what2', '2', 'UtherWhat2.wav'),
	(62, 3, 'what3', '3', 'UtherWhat3.wav'),
	(62, 3, 'what4', '4', 'UtherWhat4.wav'),
	(62, 4, 'yes1', '1', 'UtherYes1.wav'),
	(62, 4, 'yes2', '2', 'UtherYes2.wav'),
	(62, 4, 'yes3', '3', 'UtherYes3.wav'),
	(62, 4, 'yes4', '4', 'UtherYes4.wav'),
	(62, 5, 'attack1', '1', 'UtherYesAttack1.wav'),
	(62, 5, 'attack2', '2', 'UtherYesAttack2.wav'),
	(62, 5, 'attack3', '3', 'UtherYesAttack3.wav'),
	(62, 6, 'fun1', '1', 'UtherPissed1.wav'),
	(62, 6, 'fun2', '2', 'UtherPissed2.wav'),
	(62, 6, 'fun3', '3', 'UtherPissed3.wav'),
	(62, 6, 'fun4', '4', 'UtherPissed4.wav'),

	(63, 1, 'ready1', '1', 'WindserpentReady1.wav'),
	(63, 2, 'warcry1', '1', 'WindserpentWarcry1.wav'),
	(63, 3, 'what1', '1', 'WindserpentWhat1.wav'),
	(63, 3, 'what2', '2', 'WindserpentWhat2.wav'),
	(63, 3, 'what3', '3', 'WindserpentWhat3.wav'),
	(63, 4, 'yes1', '1', 'WindserpentYes1.wav'),
	(63, 4, 'yes2', '2', 'WindserpentYes2.wav'),
	(63, 4, 'yes3', '3', 'WindserpentYes3.wav'),
	(63, 5, 'attack1', '1', 'WindserpentYesAttack1.wav'),
	(63, 5, 'attack2', '2', 'WindserpentYesAttack2.wav'),
	(63, 5, 'attack3', '3', 'WindserpentYesAttack3.wav'),
	(63, 6, 'fun1', '1', 'WindserpentPissed1.wav'),
	(63, 6, 'fun2', '2', 'WindserpentPissed2.wav'),
	(63, 6, 'fun3', '3', 'WindserpentPissed3.wav'),
	(63, 6, 'fun4', '4', 'WindserpentPissed4.wav'),
	(63, 6, 'fun5', '5', 'WindserpentPissed5.wav'),

	(65, 2, 'warcry1', 'Pour le roi Térénas !', 'CaptainWarcry1.wav'),
	(65, 3, 'what1', 'Je suis prêt.', 'CaptainWhat1.wav'),
	(65, 3, 'what2', 'Que désirez-vous ?', 'CaptainWhat2.wav'),
	(65, 3, 'what3', 'Comment puis-je vous servir ?', 'CaptainWhat3.wav'),
	(65, 4, 'yes1', 'Je suis honoré.', 'CaptainYes1.wav'),
	(65, 4, 'yes2', 'Je ferai de mon mieux.', 'CaptainYes2.wav'),
	(65, 4, 'yes3', 'Pour Lordaeron !', 'CaptainYes3.wav'),
	(65, 5, 'attack1', 'Bête immonde !', 'CaptainYesAttack1.wav'),
	(65, 6, 'fun1', 'J''aurai dû écouter mon père, et devenir paysan...', 'CaptainPissed1.wav'),
	(65, 6, 'fun2', 'Danger permanent, solde de misère...', 'CaptainPissed2.wav'),
	(65, 6, 'fun3', 'Pose tes galons, qu''on s''explique entre hommes !', 'CaptainPissed3.wav'),

	-- nightelfs

	(28, 1, 'ready1', '1', 'HeroDemonHunterReady1.wav'),
	(28, 2, 'warcry1', '1', 'HeroDemonHunterWarcry1.wav'),
	(28, 3, 'what1', '1', 'HeroDemonHunterWhat1.wav'),
	(28, 3, 'what2', '2', 'HeroDemonHunterWhat2.wav'),
	(28, 3, 'what3', '3', 'HeroDemonHunterWhat3.wav'),
	(28, 3, 'what4', '4', 'HeroDemonHunterWhat5.wav'),
	(28, 3, 'what5', '5', 'HeroDemonHunterWhat4.wav'),
	(28, 4, 'yes1', '1', 'HeroDemonHunterYes1.wav'),
	(28, 4, 'yes2', '2', 'HeroDemonHunterYes2.wav'),
	(28, 4, 'yes3', '3', 'HeroDemonHunterYes3.wav'),
	(28, 4, 'yes4', '4', 'HeroDemonHunterYes4.wav'),
	(28, 4, 'yes5', '5', 'HeroDemonHunterYes5.wav'),
	(28, 5, 'attack1', '1', 'HeroDemonHunterYesAttack1.wav'),
	(28, 5, 'attack2', '2', 'HeroDemonHunterYesAttack2.wav'),
	(28, 5, 'attack3', '3', 'HeroDemonHunterYesAttack3.wav'),
	(28, 5, 'attack4', '4', 'HeroDemonHunterYesAttack4.wav'),
	(28, 6, 'fun1', '1', 'HeroDemonHunterPissed1.wav'),
	(28, 6, 'fun3', '2', 'HeroDemonHunterPissed3.wav'),
	(28, 6, 'fun4', '3', 'HeroDemonHunterPissed4.wav'),
	(28, 6, 'fun2', '4', 'HeroDemonHunterPissed2.wav'),
	(28, 6, 'fun7', '5', 'HeroDemonHunterPissed7.wav'),
	(28, 6, 'fun5', '6', 'HeroDemonHunterPissed5.wav'),
	(28, 6, 'fun6', '7', 'HeroDemonHunterPissed6.wav'),
	(28, 7, 'death1', 'Mort', 'HeroDemonHunterDeath1.wav'),

	(100, 1, 'ready1', '1', 'DemonhunterMorphedready1.wav'),
	(100, 2, 'warcry1', '1', 'DemonhunterMorphedwarcry1.wav'),
	(100, 3, 'what1', '1', 'DemonHunterMorphedWhat1.wav'),
	(100, 3, 'what2', '2', 'DemonhunterMorphedwhat2.wav'),
	(100, 3, 'what3', '3', 'DemonhunterMorphedwhat3.wav'),
	(100, 3, 'what4', '4', 'DemonhunterMorphedwhat4.wav'),
	(100, 3, 'what5', '5', 'DemonhunterMorphedwhat5.wav'),
	(100, 4, 'yes1', '1', 'DemonhunterMorphedyes1.wav'),
	(100, 4, 'yes2', '2', 'DemonhunterMorphedyes2.wav'),
	(100, 4, 'yes3', '3', 'DemonhunterMorphedyes3.wav'),
	(100, 4, 'yes4', '4', 'DemonhunterMorphedyes4.wav'),
	(100, 4, 'yes5', '5', 'DemonhunterMorphedyes5.wav'),
	(100, 5, 'attack1', '1', 'HeroDemonHunterYesAttack1.wav'),
	(100, 5, 'attack2', '2', 'HeroDemonHunterYesAttack2.wav'),
	(100, 5, 'attack3', '3', 'HeroDemonHunterYesAttack3.wav'),
	(100, 5, 'attack4', '7', 'HeroDemonHunterYesAttack4.wav'),
	(100, 6, 'fun1', '1', 'HeroDemonHunterPissed1.wav'),
	(100, 6, 'fun2', '2', 'HeroDemonHunterPissed2.wav'),
	(100, 6, 'fun3', '3', 'HeroDemonHunterPissed3.wav'),
	(100, 6, 'fun4', '4', 'HeroDemonHunterPissed4.wav'),
	(100, 6, 'fun5', '5', 'HeroDemonHunterPissed5.wav'),
	(100, 6, 'fun6', '6', 'HeroDemonHunterPissed6.wav'),
	(100, 6, 'fun7', '7', 'HeroDemonHunterPissed7.wav'),
	(100, 7, 'death1', 'Mort', 'HeroDemonHunterDeath1.wav'),

	(29, 1, 'ready1', '1', 'KeeperofthegroveReady1.wav'),
	(29, 2, 'warcry1', '1', 'KeeperofthegroveWarcry1.wav'),
	(29, 3, 'what1', '1', 'KeeperofthegroveWhat1.wav'),
	(29, 3, 'what2', '2', 'KeeperofthegroveWhat2.wav'),
	(29, 3, 'what3', '3', 'KeeperofthegroveWhat3.wav'),
	(29, 3, 'what4', '4', 'KeeperofthegroveWhat4.wav'),
	(29, 3, 'what5', '5', 'KeeperofthegroveWhat5.wav'),
	(29, 4, 'yes1', '1', 'KeeperofthegroveYes1.wav'),
	(29, 4, 'yes2', '2', 'KeeperofthegroveYes2.wav'),
	(29, 4, 'yes3', '3', 'KeeperofthegroveYes3.wav'),
	(29, 4, 'yes4', '4', 'KeeperofthegroveYes4.wav'),
	(29, 4, 'yes5', '5', 'KeeperofthegroveYes5.wav'),
	(29, 5, 'attack1', '1', 'KeeperofthegroveYesAttack1.wav'),
	(29, 5, 'attack2', '2', 'KeeperofthegroveYesAttack2.wav'),
	(29, 5, 'attack3', '3', 'KeeperofthegroveYesAttack3.wav'),
	(29, 6, 'fun1', '1', 'KeeperofthegrovePissed1.wav'),
	(29, 6, 'fun2', '2', 'KeeperofthegrovePissed2.wav'),
	(29, 6, 'fun3', '3', 'KeeperofthegrovePissed3.wav'),
	(29, 6, 'fun4', '4', 'KeeperofthegrovePissed4.wav'),
	(29, 6, 'fun5', '5', 'KeeperofthegrovePissed5.wav'),
	(29, 6, 'fun6', '6', 'KeeperofthegrovePissed6.wav'),
	(29, 7, 'death1', 'Mort', 'HeroKeeperOfTheGroveDeath1.wav'),

	(30, 1, 'ready1', '1', 'HeroMoonPriestessReady1.wav'),
	(30, 2, 'warcry1', '1', 'HeroMoonPriestessWarcry1.wav'),
	(30, 3, 'what1', '1', 'HeroMoonPriestessWhat1.wav'),
	(30, 3, 'what2', '2', 'HeroMoonPriestessWhat2.wav'),
	(30, 3, 'what3', '3', 'HeroMoonPriestessWhat3.wav'),
	(30, 3, 'what4', '4', 'HeroMoonPriestessWhat4.wav'),
	(30, 4, 'yes1', '1', 'HeroMoonPriestessYes1.wav'),
	(30, 4, 'yes2', '2', 'HeroMoonPriestessYes2.wav'),
	(30, 4, 'yes3', '3', 'HeroMoonPriestessYes3.wav'),
	(30, 4, 'yes4', '4', 'HeroMoonPriestessYes4.wav'),
	(30, 5, 'attack1', '1', 'HeroMoonPriestessYesAttack1.wav'),
	(30, 5, 'attack2', '2', 'HeroMoonPriestessYesAttack2.wav'),
	(30, 5, 'attack3', '3', 'HeroMoonPriestessYesAttack3.wav'),
	(30, 6, 'fun1', '1', 'HeroMoonPriestessPissed1.wav'),
	(30, 6, 'fun2', '2', 'HeroMoonPriestessPissed2.wav'),
	(30, 6, 'fun3', '3', 'HeroMoonPriestessPissed3.wav'),
	(30, 6, 'fun4', '4', 'HeroMoonPriestessPissed4.wav'),
	(30, 6, 'fun5', '5', 'HeroMoonPriestessPissed5.wav'),
	(30, 6, 'fun6', '6', 'HeroMoonPriestessPissed6.wav'),
	(30, 7, 'death1', 'Mort', 'HeroMoonPriestessDeath1.wav'),

	(32, 1, 'ready1', 'Je suis prête', 'ArcherReady1.wav'),
	(32, 2, 'warcry1', 'A la lumière de la lune !', 'ArcherWarcry1.wav'),
	(32, 3, 'what1', 'J''écoute.', 'ArcherWhat1.wav'),
	(32, 3, 'what2', 'Indiquez le chemin.', 'ArcherWhat2.wav'),
	(32, 3, 'what3', 'A vos ordres.', 'ArcherWhat3.wav'),
	(32, 3, 'what4', 'Je vous écoute.', 'ArcherWhat4.wav'),
	(32, 4, 'yes1', 'Bien compris.', 'ArcherYes1.wav'),
	(32, 4, 'yes2', 'Reçu.', 'ArcherYes2.wav'),
	(32, 4, 'yes3', 'Il en sera ainsi.', 'ArcherYes3.wav'),
	(32, 4, 'yes4', 'Trop facile...', 'ArcherYes4.wav'),
	(32, 5, 'attack1', 'Parée à décocher', 'ArcherYesAttack1.wav'),
	(32, 5, 'attack2', 'Feu !', 'ArcherYesAttack2.wav'),
	(32, 5, 'attack3', 'Une flèche, un mort', 'ArcherYesAttack3.wav'),
	(32, 5, 'attack4', 'Mon arc est à vos ordres !', 'ArcherYesAttack4.wav'),
	(32, 6, 'fun1', 'J''adore qu''un plan se déroule sans accroc', 'ArcherPissed1.wav'),
	(32, 6, 'fun2', 'J''aurai les salauds qui ont fait ça !', 'ArcherPissed2.wav'),
	(32, 6, 'fun3', 'Je prend aux riches pour donner aux pauvres.', 'ArcherPissed3.wav'),
	(32, 6, 'fun4', 'Où est ma pomme ?', 'ArcherPissed4.wav'),
	(32, 6, 'fun5', 'La vie c''est comme une boite de chocolats : on ne sait jamais sur quoi on va tomber.', 'ArcherPissed5.wav'),
	(32, 6, 'fun6', 'La culture, c''est comme la confiture : moins on en a, plus on l''étale.', 'ArcherPissed6.wav'),
	(32, 6, 'fun7', 'Secouez-moi, secouez-moi, sinon la pulpe, elle reste en bas.', 'ArcherPissed7.wav'),
	(32, 6, 'fun8', 'Moi je dynamite ! Je disperse, je ventile...', 'ArcherPissed8.wav'),
	(32, 7, 'death1', 'Mort', 'ArcherDeath1.wav'),

	(33, 1, 'ready1', 'Déesse, montre-moi la voie...', 'HuntressReady1.wav'),
	(33, 2, 'warcry1', 'Pour notre Mère !', 'HuntressWarcry1.wav'),
	(33, 3, 'what1', 'Faites vite.', 'HuntressWhat1.wav'),
	(33, 3, 'what2', 'En position...', 'HuntressWhat2.wav'),
	(33, 3, 'what3', 'Je suis prète.', 'HuntressWhat3.wav'),
	(33, 3, 'what4', 'Parlez...', 'HuntressWhat4.wav'),
	(33, 3, 'what5', 'Je suis à vos ordres...', 'HuntressWhat5.wav'),
	(33, 4, 'yes1', 'Absolument.', 'HuntressYes1.wav'),
	(33, 4, 'yes2', 'Je ne crains rien.', 'HuntressYes2.wav'),
	(33, 4, 'yes3', 'Comme le souhaite la déesse.', 'HuntressYes3.wav'),
	(33, 4, 'yes4', 'Je me fond dans les ténèbres.', 'HuntressYes4.wav'),
	(33, 4, 'yes5', 'Ma patience est récompensée.', 'HuntressYes5.wav'),
	(33, 5, 'attack1', 'Cherche !', 'HuntressYesAttack1.wav'),
	(33, 5, 'attack2', 'Trouve !', 'HuntressYesAttack2.wav'),
	(33, 5, 'attack3', 'Craignez la nuit !', 'HuntressYesAttack3.wav'),
	(33, 5, 'attack4', 'Faites vos prières...', 'HuntressYesAttack4.wav'),
	(33, 5, 'attack5', 'Ils vont souffrir...', 'HuntressYesAttack5.wav'),
	(33, 6, 'fun1', 'Il y a les bons chausseurs, et les mauvais chasseurs.', 'HuntressPissed1.wav'),
	(33, 6, 'fun2', 'Chasseurs, chasseuses, on vous ment, on vous spolie !', 'HuntressPissed2.wav'),
	(33, 6, 'fun3', 'Il y en a même qui m''appellent "madame" le chasseur.', 'HuntressPissed3.wav'),
	(33, 6, 'fun4', 'La Chasseresse, Diane la Chasseresse.', 'HuntressPissed4.wav'),
	(33, 6, 'fun5', 'Et ne me confondez pas avec Xena.', 'HuntressPissed5.wav'),
	(33, 6, 'fun6', 'Vous avez reçu... 1... Email.', 'HuntressPissed6.wav'),
	(33, 6, 'fun7', 'Vole, Bubo !', 'HuntressPissed7.wav'),
	(33, 6, 'fun8', 'La voie du click est impénétrable.', 'HuntressPissed8.wav'),

	(34, 1, 'ready1', '1', 'DryadReady1.wav'),
	(34, 2, 'warcry1', '1', 'DryadWarcry1.wav'),
	(34, 3, 'what1', '1', 'DryadWhat1.wav'),
	(34, 3, 'what2', '2', 'DryadWhat2.wav'),
	(34, 3, 'what3', '3', 'DryadWhat3.wav'),
	(34, 3, 'what4', '4', 'DryadWhat4.wav'),
	(34, 4, 'yes1', '1', 'DryadYes1.wav'),
	(34, 4, 'yes2', '2', 'DryadYes2.wav'),
	(34, 4, 'yes3', '3', 'DryadYes3.wav'),
	(34, 4, 'yes4', '4', 'DryadYes4.wav'),
	(34, 5, 'attack2', '2', 'DryadYesAttack2.wav'),
	(34, 5, 'attack3', '3', 'DryadYesAttack3.wav'),
	(34, 5, 'attack4', '4', 'DryadYesAttack4.wav'),
	(34, 6, 'fun1', '1', 'DryadPissed1.wav'),
	(34, 6, 'fun2', '2', 'DryadPissed2.wav'),
	(34, 6, 'fun3', '3', 'DryadPissed3.wav'),
	(34, 6, 'fun4', '4', 'DryadPissed4.wav'),
	(34, 6, 'fun5', '5', 'DryadPissed5.wav'),
	(34, 6, 'fun6', '6', 'DryadPissed6.wav'),
	(34, 6, 'fun7', '7', 'DryadPissed7.wav'),
	(34, 6, 'fun8', '8', 'DryadPissed8.wav'),
	(34, 6, 'fun9', '9', 'DryadPissed9.wav'),
	(34, 7, 'death1', 'Mort', 'DryadDeath1.wav'),

	(35, 1, 'ready1', '1', 'DruidoftheclawReady1.wav'),
	(35, 2, 'warcry1', '1', 'DruidoftheclawWarcry1.wav'),
	(35, 3, 'what1', '1', 'DruidoftheclawWhat1.wav'),
	(35, 3, 'what2', '2', 'DruidoftheclawWhat2.wav'),
	(35, 3, 'what3', '3', 'DruidoftheclawWhat3.wav'),
	(35, 3, 'what4', '4', 'DruidoftheclawWhat4.wav'),
	(35, 4, 'yes1', '1', 'DruidoftheclawYes1.wav'),
	(35, 4, 'yes2', '2', 'DruidoftheclawYes2.wav'),
	(35, 4, 'yes3', '3', 'DruidoftheclawYes3.wav'),
	(35, 4, 'yes4', '4', 'DruidoftheclawYes4.wav'),
	(35, 5, 'attack1', '1', 'DruidoftheclawYesAttack1.wav'),
	(35, 5, 'attack2', '2', 'DruidoftheclawYesAttack2.wav'),
	(35, 5, 'attack3', '3', 'DruidoftheclawYesAttack3.wav'),
	(35, 6, 'fun1', '1', 'DruidoftheclawPissed1.wav'),
	(35, 6, 'fun2', '2', 'DruidoftheclawPissed2.wav'),
	(35, 6, 'fun3', '3', 'DruidoftheclawPissed3.wav'),
	(35, 6, 'fun4', '4', 'DruidoftheclawPissed4.wav'),
	(35, 6, 'fun5', '5', 'DruidoftheclawPissed5.wav'),
	(35, 6, 'fun6', '6', 'DruidoftheclawPissed6.wav'),
	(35, 6, 'fun7', '7', 'DruidoftheclawPissed7.wav'),
	(35, 7, 'death1', 'Mort', 'DruidoftheclawDeath1.wav'),

	(36, 1, 'ready1', '1', 'DruidofthetalonReady1.wav'),
	(36, 2, 'warcry1', '1', 'DruidofthetalonWarcry1.wav'),
	(36, 3, 'what1', '1', 'DruidofthetalonWhat1.wav'),
	(36, 3, 'what2', '2', 'DruidofthetalonWhat2.wav'),
	(36, 3, 'what3', '3', 'DruidofthetalonWhat3.wav'),
	(36, 3, 'what4', '4', 'DruidofthetalonWhat4.wav'),
	(36, 4, 'yes1', '1', 'DruidofthetalonYes1.wav'),
	(36, 4, 'yes2', '2', 'DruidofthetalonYes2.wav'),
	(36, 4, 'yes3', '3', 'DruidofthetalonYes3.wav'),
	(36, 4, 'yes4', '4', 'DruidofthetalonYes4.wav'),
	(36, 5, 'attack1', '1', 'DruidofthetalonYesAttack1.wav'),
	(36, 5, 'attack2', '2', 'DruidofthetalonYesAttack2.wav'),
	(36, 5, 'attack3', '3', 'DruidofthetalonYesAttack3.wav'),
	(36, 6, 'fun1', '1', 'DruidofthetalonPissed1.wav'),
	(36, 6, 'fun2', '2', 'DruidofthetalonPissed2.wav'),
	(36, 6, 'fun3', '3', 'DruidofthetalonPissed3.wav'),
	(36, 6, 'fun4', '4', 'DruidofthetalonPissed4.wav'),
	(36, 6, 'fun5', '5', 'DruidofthetalonPissed5.wav'),
	(36, 6, 'fun6', '6', 'DruidofthetalonPissed6.wav'),
	(36, 6, 'fun7', '7', 'DruidofthetalonPissed7.wav'),
	(36, 7, 'death1', 'Mort', 'DruidofthetalonDeath1.wav'),

	(37, 1, 'ready1', '1', 'HippogryphWithRiderReady1.wav'),
	(37, 2, 'warcry1', '1', 'HippogryphWithRiderWarcry1.wav'),
	(37, 3, 'what1', '1', 'HippogryphWithRiderWhat1.wav'),
	(37, 3, 'what2', '2', 'HippogryphWithRiderWhat2.wav'),
	(37, 3, 'what3', '3', 'HippogryphWithRiderWhat3.wav'),
	(37, 4, 'yes1', '1', 'HippogryphWithRiderYes1.wav'),
	(37, 4, 'yes2', '2', 'HippogryphWithRiderYes2.wav'),
	(37, 4, 'yes3', '3', 'HippogryphWithRiderYes3.wav'),
	(37, 4, 'yes4', '4', 'HippogryphWithRiderYes4.wav'),
	(37, 5, 'attack1', '1', 'HippogryphWithRiderYesAttack1.wav'),
	(37, 5, 'attack2', '2', 'HippogryphWithRiderYesAttack2.wav'),
	(37, 5, 'attack3', '3', 'HippogryphWithRiderYesAttack3.wav'),
	(37, 6, 'fun1', '1', 'HippogryphWithRiderPissed1.wav'),
	(37, 6, 'fun2', '2', 'HippogryphWithRiderPissed2.wav'),
	(37, 6, 'fun3', '3', 'HippogryphWithRiderPissed3.wav'),
	(37, 6, 'fun4', '4', 'HippogryphWithRiderPissed4.wav'),

	(73, 2, 'warcry1', '1', 'FurionWarcry1.wav'),
	(73, 3, 'what1', '1', 'FurionWhat1.wav'),
	(73, 3, 'what2', '2', 'FurionWhat2.wav'),
	(73, 3, 'what3', '3', 'FurionWhat3.wav'),
	(73, 3, 'what4', '4', 'FurionWhat4.wav'),
	(73, 4, 'yes1', '1', 'FurionYes1.wav'),
	(73, 4, 'yes2', '2', 'FurionYes2.wav'),
	(73, 4, 'yes3', '3', 'FurionYes3.wav'),
	(73, 4, 'yes4', '4', 'FurionYes4.wav'),
	(73, 5, 'attack1', '1', 'FurionYesAttack1.wav'),
	(73, 5, 'attack2', '2', 'FurionYesAttack2.wav'),
	(73, 5, 'attack3', '3', 'FurionYesAttack3.wav'),
	(73, 5, 'attack4', '4', 'FurionYesAttack4.wav'),
	(73, 6, 'fun1', '1', 'FurionPissed1.wav'),
	(73, 6, 'fun2', '2', 'FurionPissed2.wav'),
	(73, 6, 'fun3', '3', 'FurionPissed3.wav'),
	(73, 6, 'fun4', '4', 'FurionPissed4.wav'),
	(73, 6, 'fun5', '5', 'FurionPissed5.wav'),

	(74, 2, 'warcry1', '1', 'IllidanWarcry1.wav'),
	(74, 3, 'what1', '1', 'IllidanWhat1.wav'),
	(74, 3, 'what2', '2', 'IllidanWhat2.wav'),
	(74, 3, 'what3', '3', 'IllidanWhat3.wav'),
	(74, 3, 'what4', '4', 'IllidanWhat4.wav'),
	(74, 4, 'yes1', '1', 'IllidanYes1.wav'),
	(74, 4, 'yes2', '2', 'IllidanYes2.wav'),
	(74, 4, 'yes3', '3', 'IllidanYes3.wav'),
	(74, 4, 'yes4', '4', 'IllidanYes4.wav'),
	(74, 5, 'attack1', '1', 'IllidanYesAttack1.wav'),
	(74, 5, 'attack2', '2', 'IllidanYesAttack2.wav'),
	(74, 5, 'attack3', '3', 'IllidanYesAttack3.wav'),
	(74, 6, 'fun1', '1', 'IllidanPissed1.wav'),
	(74, 6, 'fun2', '2', 'IllidanPissed2.wav'),
	(74, 6, 'fun3', '3', 'IllidanPissed3.wav'),
	(74, 6, 'fun4', '4', 'IllidanPissed4.wav'),
	(74, 6, 'fun5', '5', 'IllidanPissed5.wav'),

	(75, 2, 'warcry1', '1', 'IllidanmorphedWarcry1.wav'),
	(75, 3, 'what1', '1', 'IllidanmorphedWhat1.wav'),
	(75, 3, 'what2', '2', 'IllidanmorphedWhat2.wav'),
	(75, 3, 'what3', '3', 'IllidanmorphedWhat3.wav'),
	(75, 3, 'what4', '4', 'IllidanmorphedWhat4.wav'),
	(75, 4, 'yes1', '1', 'IllidanmorphedYes1.wav'),
	(75, 4, 'yes2', '2', 'IllidanmorphedYes2.wav'),
	(75, 4, 'yes3', '3', 'IllidanmorphedYes3.wav'),
	(75, 4, 'yes4', '4', 'IllidanmorphedYes4.wav'),
	(75, 5, 'attack1', '1', 'IllidanmorphedYesAttack1.wav'),
	(75, 5, 'attack2', '2', 'IllidanmorphedYesAttack2.wav'),
	(75, 5, 'attack3', '3', 'IllidanmorphedYesAttack3.wav'),
	(75, 6, 'fun1', '1', 'IllidanmorphedPissed1.wav'),
	(75, 6, 'fun2', '2', 'IllidanmorphedPissed2.wav'),
	(75, 6, 'fun3', '3', 'IllidanmorphedPissed3.wav'),
	(75, 6, 'fun4', '4', 'IllidanmorphedPissed4.wav'),
	(75, 6, 'fun5', '5', 'IllidanmorphedPissed5.wav'),

	(76, 2, 'warcry1', '1', 'ShandrisWarcry1.wav'),
	(76, 3, 'what1', '1', 'ShandrisWhat1.wav'),
	(76, 3, 'what2', '2', 'ShandrisWhat2.wav'),
	(76, 3, 'what3', '3', 'ShandrisWhat3.wav'),
	(76, 4, 'yes1', '1', 'ShandrisYes1.wav'),
	(76, 4, 'yes2', '2', 'ShandrisYes2.wav'),
	(76, 4, 'yes3', '3', 'ShandrisYes3.wav'),
	(76, 5, 'attack1', '1', 'ShandrisYesAttack1.wav'),
	(76, 5, 'attack2', '2', 'ShandrisYesAttack2.wav'),
	(76, 5, 'attack3', '3', 'ShandrisYesAttack3.wav'),
	(76, 6, 'fun1', '1', 'ShandrisPissed1.wav'),
	(76, 6, 'fun2', '2', 'ShandrisPissed2.wav'),
	(76, 6, 'fun3', '3', 'ShandrisPissed3.wav'),
	(76, 6, 'fun4', '4', 'ShandrisPissed4.wav'),

	(77, 2, 'warcry1', '1', 'SylvanasWarcry1.wav'),
	(77, 3, 'what1', '1', 'SylvanasWhat1.wav'),
	(77, 3, 'what2', '2', 'SylvanasWhat2.wav'),
	(77, 3, 'what3', '3', 'SylvanasWhat3.wav'),
	(77, 3, 'what4', '4', 'SylvanasWhat4.wav'),
	(77, 6, 'fun1', '1', 'SylvanasPissed1.wav'),
	(77, 6, 'fun2', '2', 'SylvanasPissed2.wav'),
	(77, 6, 'fun3', '3', 'SylvanasPissed3.wav'),
	(77, 6, 'fun4', '4', 'SylvanasPissed4.wav'),
	(77, 6, 'fun5', '5', 'SylvanasPissed5.wav'),

	(78, 2, 'warcry1', '1', 'TyrandeWarcry1.wav'),
	(78, 3, 'what1', '1', 'TyrandeWhat1.wav'),
	(78, 3, 'what2', '2', 'TyrandeWhat2.wav'),
	(78, 3, 'what3', '3', 'TyrandeWhat3.wav'),
	(78, 3, 'what4', '4', 'TyrandeWhat4.wav'),
	(78, 4, 'yes1', '1', 'TyrandeYes1.wav'),
	(78, 4, 'yes2', '2', 'TyrandeYes2.wav'),
	(78, 4, 'yes3', '3', 'TyrandeYes3.wav'),
	(78, 4, 'yes4', '4', 'TyrandeYes4.wav'),
	(78, 5, 'attack1', '1', 'TyrandeYesAttack1.wav'),
	(78, 5, 'attack2', '2', 'TyrandeYesAttack2.wav'),
	(78, 5, 'attack3', '3', 'TyrandeYesAttack3.wav'),
	(78, 5, 'attack4', '4', 'TyrandeYesAttack4.wav'),
	(78, 6, 'fun1', '1', 'TyrandePissed1.wav'),
	(78, 6, 'fun2', '2', 'TyrandePissed2.wav'),
	(78, 6, 'fun3', '3', 'TyrandePissed3.wav'),
	(78, 6, 'fun4', '4', 'TyrandePissed4.wav'),
	(78, 6, 'fun5', '5', 'TyrandePissed5.wav'),

	-- orcs

	(15, 1, 'ready1', '1', 'HeroBlademasterReady1.wav'),
	(15, 2, 'warcry1', '1', 'HeroBlademasterWarcry1.wav'),
	(15, 3, 'what1', '1', 'HeroBlademasterWhat1.wav'),
	(15, 3, 'what2', '2', 'HeroBlademasterWhat2.wav'),
	(15, 3, 'what3', '3', 'HeroBlademasterWhat3.wav'),
	(15, 3, 'what4', '4', 'HeroBlademasterWhat4.wav'),
	(15, 4, 'yes1', '1', 'HeroBlademasterYes1.wav'),
	(15, 4, 'yes2', '2', 'HeroBlademasterYes2.wav'),
	(15, 4, 'yes3', '3', 'HeroBlademasterYes3.wav'),
	(15, 4, 'yes4', '4', 'HeroBlademasterYes4.wav'),
	(15, 5, 'attack1', '1', 'HeroBlademasterYesAttack1.wav'),
	(15, 5, 'attack2', '2', 'HeroBlademasterYesAttack2.wav'),
	(15, 5, 'attack3', '3', 'HeroBlademasterYesAttack3.wav'),
	(15, 6, 'fun1', '1', 'HeroBlademasterPissed1.wav'),
	(15, 6, 'fun2', '2', 'HeroBlademasterPissed2.wav'),
	(15, 6, 'fun3', '3', 'HeroBlademasterPissed3.wav'),
	(15, 6, 'fun4', '4', 'HeroBlademasterPissed4.wav'),
	(15, 7, 'death1', 'Mort', 'HeroBladeMasterDeath.wav'),

	(16, 1, 'ready1', '1', 'HeroFarseerReady1.wav'),
	(16, 2, 'warcry1', '1', 'HeroFarseerWarcry1.wav'),
	(16, 3, 'what1', '1', 'HeroFarseerWhat1.wav'),
	(16, 3, 'what2', '2', 'HeroFarseerWhat1.wav'),
	(16, 3, 'what3', '3', 'HeroFarseerWhat2.wav'),
	(16, 3, 'what4', '4', 'HeroFarseerWhat3.wav'),
	(16, 4, 'yes1', '1', 'HeroFarseerYes1.wav'),
	(16, 4, 'yes2', '2', 'HeroFarseerYes2.wav'),
	(16, 4, 'yes3', '3', 'HeroFarseerYes3.wav'),
	(16, 4, 'yes4', '4', 'HeroFarseerYes4.wav'),
	(16, 5, 'attack1', '1', 'HeroFarseerYesAttack1.wav'),
	(16, 5, 'attack2', '2', 'HeroFarseerYesAttack2.wav'),
	(16, 5, 'attack3', '3', 'HeroFarseerYesAttack3.wav'),
	(16, 6, 'fun1', '1', 'HeroFarseerPissed1.wav'),
	(16, 6, 'fun2', '2', 'HeroFarseerPissed2.wav'),
	(16, 6, 'fun3', '3', 'HeroFarseerPissed3.wav'),
	(16, 6, 'fun4', '4', 'HeroFarseerPissed4.wav'),
	(16, 6, 'fun5', '5', 'HeroFarseerPissed5.wav'),
	(16, 7, 'death1', 'Mort', 'HeroFarseerDeath1.wav'),

	(17, 1, 'ready1', '1', 'HeroTaurenChieftainReady1.wav'),
	(17, 2, 'warcry1', '1', 'HeroTaurenChieftainWarcry1.wav'),
	(17, 3, 'what1', '1', 'HeroTaurenChieftainWhat1.wav'),
	(17, 3, 'what2', '2', 'HeroTaurenChieftainWhat2.wav'),
	(17, 3, 'what3', '3', 'HeroTaurenChieftainWhat3.wav'),
	(17, 3, 'what4', '4', 'HeroTaurenChieftainWhat4.wav'),
	(17, 4, 'yes1', '1', 'HeroTaurenChieftainYes1.wav'),
	(17, 4, 'yes2', '2', 'HeroTaurenChieftainYes2.wav'),
	(17, 4, 'yes3', '3', 'HeroTaurenChieftainYes3.wav'),
	(17, 4, 'yes4', '4', 'HeroTaurenChieftainYes4.wav'),
	(17, 5, 'attack1', '1', 'HeroTaurenChieftainYesAttack1.wav'),
	(17, 5, 'attack2', '2', 'HeroTaurenChieftainYesAttack2.wav'),
	(17, 5, 'attack3', '3', 'HeroTaurenChieftainYesAttack3.wav'),
	(17, 6, 'fun1', '1', 'HeroTaurenChieftainPissed1.wav'),
	(17, 6, 'fun2', '2', 'HeroTaurenChieftainPissed2.wav'),
	(17, 6, 'fun3', '3', 'HeroTaurenChieftainPissed3.wav'),
	(17, 6, 'fun4', '4', 'HeroTaurenChieftainPissed4.wav'),
	(17, 6, 'fun5', '5', 'HeroTaurenChieftainPissed5.wav'),
	(17, 6, 'fun6', '6', 'HeroTaurenChieftainPissed6.wav'),
	(17, 7, 'death1', 'Mort', 'HeroTaurenChieftainDeath.wav'),

	(19, 1, 'ready1', '1', 'PeonReady1.wav'),
	(19, 2, 'warcry1', '1', 'PeonWarcry1.wav'),
	(19, 3, 'what1', '1', 'PeonWhat1.wav'),
	(19, 3, 'what2', '2', 'PeonWhat2.wav'),
	(19, 3, 'what3', '3', 'PeonWhat3.wav'),
	(19, 3, 'what4', '4', 'PeonWhat4.wav'),
	(19, 4, 'yes1', '1', 'PeonYes1.wav'),
	(19, 4, 'yes2', '2', 'PeonYes2.wav'),
	(19, 4, 'yes3', '3', 'PeonYes3.wav'),
	(19, 4, 'yes4', '4', 'PeonYes4.wav'),
	(19, 5, 'attack1', '1', 'PeonYesAttack1.wav'),
	(19, 5, 'attack2', '2', 'PeonYesAttack2.wav'),
	(19, 5, 'attack3', '3', 'PeonYesAttack3.wav'),
	(19, 6, 'fun1', '1', 'PeonPissed1.wav'),
	(19, 6, 'fun2', '2', 'PeonPissed2.wav'),
	(19, 6, 'fun3', '3', 'PeonPissed3.wav'),
	(19, 6, 'fun4', '4', 'PeonPissed4.wav'),
	(19, 7, 'death1', 'Mort', 'PeonDeath.wav'),

	(20, 1, 'ready1', '1', 'GruntReady1.wav'),
	(20, 2, 'warcry1', '1', 'GruntWarcry1.wav'),
	(20, 3, 'what1', '1', 'GruntWhat1.wav'),
	(20, 3, 'what2', '2', 'GruntWhat2.wav'),
	(20, 3, 'what3', '3', 'GruntWhat3.wav'),
	(20, 3, 'what4', '4', 'GruntWhat4.wav'),
	(20, 4, 'yes1', '1', 'GruntYes1.wav'),
	(20, 4, 'yes2', '2', 'GruntYes2.wav'),
	(20, 4, 'yes3', '3', 'GruntYes3.wav'),
	(20, 4, 'yes4', '4', 'GruntYes4.wav'),
	(20, 5, 'attack1', '1', 'GruntYesAttack1.wav'),
	(20, 5, 'attack2', '2', 'GruntYesAttack2.wav'),
	(20, 5, 'attack3', '3', 'GruntYesAttack3.wav'),
	(20, 6, 'fun1', '1', 'GruntPissed1.wav'),
	(20, 6, 'fun2', '2', 'GruntPissed2.wav'),
	(20, 6, 'fun3', '3', 'GruntPissed3.wav'),
	(20, 6, 'fun4', '4', 'GruntPissed4.wav'),
	(20, 6, 'fun5', '5', 'GruntPissed5.wav'),
	(20, 6, 'fun6', '6', 'GruntPissed6.wav'),
	(20, 6, 'fun7', '7', 'GruntPissed7.wav'),
	(20, 7, 'death1', 'Mort', 'GruntDeath.wav'),

	(21, 1, 'ready1', '1', 'HeadhunterReady1.wav'),
	(21, 2, 'warcry1', '1', 'HeadhunterWarcry1.wav'),
	(21, 3, 'what1', '1', 'HeadhunterWhat1.wav'),
	(21, 3, 'what2', '2', 'HeadhunterWhat2.wav'),
	(21, 3, 'what3', '3', 'HeadhunterWhat3.wav'),
	(21, 3, 'what4', '4', 'HeadhunterWhat4.wav'),
	(21, 4, 'yes1', '1', 'HeadhunterYes1.wav'),
	(21, 4, 'yes2', '2', 'HeadhunterYes2.wav'),
	(21, 4, 'yes3', '3', 'HeadhunterYes3.wav'),
	(21, 4, 'yes4', '4', 'HeadhunterYes4.wav'),
	(21, 5, 'attack1', '1', 'HeadhunterYesAttack1.wav'),
	(21, 5, 'attack2', '2', 'HeadhunterYesAttack2.wav'),
	(21, 5, 'attack3', '3', 'HeadhunterYesAttack3.wav'),
	(21, 6, 'fun1', '1', 'HeadhunterPissed1.wav'),
	(21, 6, 'fun2', '2', 'HeadhunterPissed2.wav'),
	(21, 6, 'fun3', '3', 'HeadhunterPissed3.wav'),
	(21, 6, 'fun4', '4', 'HeadhunterPissed4.wav'),
	(21, 6, 'fun5', '5', 'HeadhunterPissed5.wav'),
	(21, 7, 'death1', 'Mort', 'HeadhunterDeath.wav'),

	(22, 1, 'ready1', '1', 'WolfriderReady1.wav'),
	(22, 2, 'warcry1', '1', 'WolfriderWarcry1.wav'),
	(22, 3, 'what1', '1', 'WolfriderWhat1.wav'),
	(22, 3, 'what2', '2', 'WolfriderWhat2.wav'),
	(22, 3, 'what3', '3', 'WolfriderWhat3.wav'),
	(22, 3, 'what4', '4', 'WolfriderWhat4.wav'),
	(22, 4, 'yes1', '1', 'WolfriderYes1.wav'),
	(22, 4, 'yes2', '2', 'WolfriderYes2.wav'),
	(22, 4, 'yes3', '3', 'WolfriderYes3.wav'),
	(22, 4, 'yes4', '4', 'WolfriderYes4.wav'),
	(22, 5, 'attack1', '1', 'WolfriderYesAttack1.wav'),
	(22, 5, 'attack2', '2', 'WolfriderYesAttack2.wav'),
	(22, 5, 'attack3', '3', 'WolfriderYesAttack3.wav'),
	(22, 6, 'fun1', '1', 'WolfriderPissed1.wav'),
	(22, 6, 'fun2', '2', 'WolfriderPissed2.wav'),
	(22, 6, 'fun3', '3', 'WolfriderPissed3.wav'),
	(22, 6, 'fun4', '4', 'WolfriderPissed4.wav'),

	(23, 1, 'ready1', '1', 'WyvernriderReady1.wav'),
	(23, 2, 'warcry1', '1', 'WyvernriderWarcry1.wav'),
	(23, 3, 'what1', '1', 'WyvernriderWhat1.wav'),
	(23, 3, 'what2', '2', 'WyvernriderWhat2.wav'),
	(23, 3, 'what3', '3', 'WyvernriderWhat3.wav'),
	(23, 3, 'what4', '4', 'WyvernriderWhat4.wav'),
	(23, 4, 'yes1', '1', 'WyvernriderYes1.wav'),
	(23, 4, 'yes2', '2', 'WyvernriderYes2.wav'),
	(23, 4, 'yes3', '3', 'WyvernriderYes3.wav'),
	(23, 4, 'yes4', '4', 'WyvernriderYes4.wav'),
	(23, 5, 'attack1', '1', 'WyvernriderYesAttack1.wav'),
	(23, 5, 'attack2', '2', 'WyvernriderYesAttack2.wav'),
	(23, 5, 'attack3', '3', 'WyvernriderYesAttack3.wav'),
	(23, 5, 'attack4', '4', 'WyvernriderYesAttack4.wav'),
	(23, 6, 'fun1', '1', 'WyvernriderPissed1.wav'),
	(23, 6, 'fun2', '2', 'WyvernriderPissed2.wav'),
	(23, 6, 'fun3', '3', 'WyvernriderPissed3.wav'),
	(23, 6, 'fun4', '4', 'WyvernriderPissed4.wav'),
	(23, 6, 'fun5', '5', 'WyvernriderPissed5.wav'),
	(23, 6, 'fun6', '6', 'WyvernriderPissed6.wav'),
	(23, 6, 'fun7', '7', 'WyvernriderPissed7.wav'),
	(23, 7, 'death1', 'Mort', 'WyvernriderDeath.wav'),

	(24, 1, 'ready1', '1', 'TaurenReady1.wav'),
	(24, 2, 'warcry1', '1', 'TaurenWarcry1.wav'),
	(24, 3, 'what1', '1', 'TaurenWhat1.wav'),
	(24, 3, 'what2', '2', 'TaurenWhat2.wav'),
	(24, 3, 'what3', '3', 'TaurenWhat3.wav'),
	(24, 4, 'yes1', '1', 'TaurenYes1.wav'),
	(24, 4, 'yes2', '2', 'TaurenYes2.wav'),
	(24, 4, 'yes3', '3', 'TaurenYes3.wav'),
	(24, 5, 'attack1', '1', 'TaurenYesAttack1.wav'),
	(24, 5, 'attack2', '2', 'TaurenYesAttack2.wav'),
	(24, 5, 'attack3', '3', 'TaurenYesAttack3.wav'),
	(24, 6, 'fun1', '1', 'TaurenPissed1.wav'),
	(24, 6, 'fun2', '2', 'TaurenPissed2.wav'),
	(24, 6, 'fun3', '3', 'TaurenPissed3.wav'),
	(24, 6, 'fun4', '4', 'TaurenPissed4.wav'),
	(24, 6, 'fun5', '5', 'TaurenPissed5.wav'),
	(24, 6, 'fun6', '6', 'TaurenPissed6.wav'),
	(24, 6, 'fun7', '7', 'TaurenPissed7.wav'),
	(24, 7, 'death1', 'Mort', 'TaurenDeath1.wav'),

	(25, 1, 'ready1', '1', 'ShamanReady1.wav'),
	(25, 2, 'warcry1', '1', 'ShamanWarcry1.wav'),
	(25, 3, 'what1', '1', 'ShamanWhat1.wav'),
	(25, 3, 'what2', '2', 'ShamanWhat2.wav'),
	(25, 3, 'what3', '3', 'ShamanWhat3.wav'),
	(25, 3, 'what4', '4', 'ShamanWhat4.wav'),
	(25, 4, 'yes1', '1', 'ShamanYes1.wav'),
	(25, 4, 'yes2', '2', 'ShamanYes2.wav'),
	(25, 4, 'yes3', '3', 'ShamanYes3.wav'),
	(25, 4, 'yes4', '4', 'ShamanYes4.wav'),
	(25, 5, 'attack1', '1', 'ShamanYesAttack1.wav'),
	(25, 5, 'attack2', '2', 'ShamanYesAttack2.wav'),
	(25, 5, 'attack3', '3', 'ShamanYesAttack3.wav'),
	(25, 5, 'attack4', '4', 'ShamanYesAttack4.wav'),
	(25, 6, 'fun1', '1', 'ShamanPissed1.wav'),
	(25, 6, 'fun2', '2', 'ShamanPissed2.wav'),
	(25, 6, 'fun3', '3', 'ShamanPissed3.wav'),
	(25, 6, 'fun4', '4', 'ShamanPissed4.wav'),
	(25, 6, 'fun5', '5', 'ShamanPissed5.wav'),
	(25, 6, 'fun6', '6', 'ShamanPissed6.wav'),
	(25, 6, 'fun7', '7', 'ShamanPissed7.wav'),
	(25, 7, 'death1', 'Mort', 'ShamanDeath.wav'),

	(26, 1, 'ready1', '1', 'WitchdoctorReady1.wav'),
	(26, 2, 'warcry1', '1', 'WitchdoctorWarcry1.wav'),
	(26, 3, 'what1', '1', 'WitchdoctorWhat1.wav'),
	(26, 3, 'what2', '2', 'WitchdoctorWhat2.wav'),
	(26, 3, 'what3', '3', 'WitchdoctorWhat3.wav'),
	(26, 3, 'what4', '4', 'WitchdoctorWhat4.wav'),
	(26, 4, 'yes1', '1', 'WitchdoctorYes1.wav'),
	(26, 4, 'yes2', '2', 'WitchdoctorYes2.wav'),
	(26, 4, 'yes3', '3', 'WitchdoctorYes3.wav'),
	(26, 5, 'attack1', '1', 'WitchdoctorYesAttack1.wav'),
	(26, 5, 'attack2', '2', 'WitchdoctorYesAttack2.wav'),
	(26, 5, 'attack3', '3', 'WitchdoctorYesAttack3.wav'),
	(26, 6, 'fun1', '1', 'WitchdoctorPissed1.wav'),
	(26, 6, 'fun2', '2', 'WitchdoctorPissed2.wav'),
	(26, 6, 'fun3', '3', 'WitchdoctorPissed3.wav'),
	(26, 6, 'fun4', '4', 'WitchdoctorPissed4.wav'),
	(26, 6, 'fun5', '5', 'WitchdoctorPissed5.wav'),
	(26, 6, 'fun6', '6', 'WitchdoctorPissed6.wav'),
	(26, 6, 'fun7', '7', 'WitchdoctorPissed7.wav'),
	(26, 7, 'death1', 'Mort', 'WitchdoctorDeath.wav'),

	(79, 2, 'warcry1', '1', 'CairneWarcry1.wav'),
	(79, 3, 'what1', '1', 'CairneWhat1.wav'),
	(79, 3, 'what2', '2', 'CairneWhat2.wav'),
	(79, 3, 'what3', '3', 'CairneWhat3.wav'),
	(79, 3, 'what4', '4', 'CairneWhat4.wav'),
	(79, 4, 'yes1', '1', 'CairneYes1.wav'),
	(79, 4, 'yes2', '2', 'CairneYes2.wav'),
	(79, 4, 'yes3', '3', 'CairneYes3.wav'),
	(79, 4, 'yes4', '4', 'CairneYes4.wav'),
	(79, 5, 'attack1', '1', 'CairneYesAttack1.wav'),
	(79, 5, 'attack2', '2', 'CairneYesAttack2.wav'),
	(79, 5, 'attack3', '3', 'CairneYesAttack3.wav'),
	(79, 5, 'attack4', '4', 'CairneYesAttack4.wav'),
	(79, 6, 'fun1', '1', 'CairnePissed1.wav'),
	(79, 6, 'fun2', '2', 'CairnePissed2.wav'),
	(79, 6, 'fun3', '3', 'CairnePissed3.wav'),
	(79, 6, 'fun4', '4', 'CairnePissed4.wav'),
	(79, 6, 'fun5', '5', 'CairnePissed5.wav'),

	(80, 2, 'warcry1', '1', 'GromWarcry1.wav'),
	(80, 3, 'what1', '1', 'GromWhat1.wav'),
	(80, 3, 'what2', '2', 'GromWhat2.wav'),
	(80, 3, 'what3', '3', 'GromWhat3.wav'),
	(80, 4, 'yes1', '1', 'GromYes1.wav'),
	(80, 4, 'yes2', '2', 'GromYes2.wav'),
	(80, 4, 'yes3', '3', 'GromYes3.wav'),
	(80, 5, 'attack1', '1', 'GromYesAttack1.wav'),
	(80, 5, 'attack2', '2', 'GromYesAttack2.wav'),
	(80, 5, 'attack3', '3', 'GromYesAttack3.wav'),
	(80, 5, 'attack4', '4', 'GromYesAttack4.wav'),
	(80, 6, 'fun1', '1', 'GromPissed1.wav'),
	(80, 6, 'fun2', '2', 'GromPissed2.wav'),
	(80, 6, 'fun3', '3', 'GromPissed3.wav'),

	(81, 2, 'warcry1', '1', 'ThrallWarcry1.wav'),
	(81, 3, 'what1', '1', 'ThrallWhat1.wav'),
	(81, 3, 'what2', '2', 'ThrallWhat2.wav'),
	(81, 3, 'what3', '3', 'ThrallWhat3.wav'),
	(81, 3, 'what4', '4', 'ThrallWhat4.wav'),
	(81, 4, 'yes1', '1', 'ThrallYes1.wav'),
	(81, 4, 'yes2', '2', 'ThrallYes2.wav'),
	(81, 4, 'yes3', '3', 'ThrallYes3.wav'),
	(81, 4, 'yes4', '4', 'ThrallYes4.wav'),
	(81, 5, 'attack1', '1', 'ThrallYesAttack1.wav'),
	(81, 5, 'attack2', '2', 'ThrallYesAttack2.wav'),
	(81, 5, 'attack3', '3', 'ThrallYesAttack3.wav'),
	(81, 5, 'attack4', '4', 'ThrallYesAttack4.wav'),
	(81, 6, 'fun1', '1', 'ThrallPissed1.wav'),
	(81, 6, 'fun2', '2', 'ThrallPissed2.wav'),
	(81, 6, 'fun3', '3', 'ThrallPissed3.wav'),
	(81, 6, 'fun4', '4', 'ThrallPissed4.wav'),

	(82, 1, 'ready1', '1', 'WarlordReady1.wav'),
	(82, 2, 'warcry1', '1', 'WarlordWarcry1.wav'),
	(82, 3, 'what1', '1', 'WarlordWhat1.wav'),
	(82, 3, 'what2', '2', 'WarlordWhat2.wav'),
	(82, 3, 'what3', '3', 'WarlordWhat3.wav'),
	(82, 4, 'yes1', '1', 'WarlordYes1.wav'),
	(82, 4, 'yes2', '2', 'WarlordYes2.wav'),
	(82, 4, 'yes3', '3', 'WarlordYes3.wav'),
	(82, 4, 'yes4', '4', 'WarlordYes4.wav'),
	(82, 5, 'attack1', '1', 'WarlordYesAttack1.wav'),
	(82, 5, 'attack2', '2', 'WarlordYesAttack2.wav'),
	(82, 5, 'attack3', '3', 'WarlordYesAttack3.wav'),
	(82, 5, 'attack4', '4', 'WarlordYesAttack4.wav'),
	(82, 5, 'attack5', '5', 'WarlordYesAttack5.wav'),
	(82, 6, 'fun1', '1', 'WarlordPissed1.wav'),
	(82, 6, 'fun2', '2', 'WarlordPissed2.wav'),

	-- undeads

	(38, 1, 'ready1', '1', 'DeathknightReady1.wav'),
	(38, 2, 'warcry1', '1', 'DeathknightWarcry1.wav'),
	(38, 3, 'what1', '1', 'DeathknightWhat1.wav'),
	(38, 3, 'what2', '2', 'DeathknightWhat2.wav'),
	(38, 3, 'what3', '3', 'DeathknightWhat3.wav'),
	(38, 3, 'what4', '4', 'DeathknightWhat4.wav'),
	(38, 4, 'yes1', '1', 'DeathknightYes1.wav'),
	(38, 4, 'yes2', '2', 'DeathknightYes2.wav'),
	(38, 4, 'yes3', '3', 'DeathknightYes3.wav'),
	(38, 4, 'yes4', '4', 'DeathknightYes4.wav'),
	(38, 4, 'yes5', '5', 'DeathknightYes5.wav'),
	(38, 5, 'attack1', '1', 'DeathknightYesAttack1.wav'),
	(38, 5, 'attack2', '2', 'DeathknightYesAttack2.wav'),
	(38, 5, 'attack3', '3', 'DeathknightYesAttack3.wav'),
	(38, 6, 'fun1', '1', 'DeathknightPissed1.wav'),
	(38, 6, 'fun2', '2', 'DeathknightPissed2.wav'),
	(38, 6, 'fun3', '3', 'DeathknightPissed3.wav'),
	(38, 6, 'fun4', '4', 'DeathknightPissed4.wav'),
	(38, 6, 'fun5', '5', 'DeathknightPissed5.wav'),
	(38, 6, 'fun6', '6', 'DeathknightPissed6.wav'),
	(38, 7, 'death1', 'Mort', 'HeroDeathKnightDeath.wav'),

	(39, 1, 'ready1', '1', 'HeroLichReady1.wav'),
	(39, 2, 'warcry1', '1', 'HeroLichWarcry1.wav'),
	(39, 3, 'what1', '1', 'HeroLichWhat1.wav'),
	(39, 3, 'what2', '2', 'HeroLichWhat2.wav'),
	(39, 3, 'what3', '3', 'HeroLichWhat3.wav'),
	(39, 3, 'what4', '4', 'HeroLichWhat4.wav'),
	(39, 4, 'yes1', '1', 'HeroLichYes1.wav'),
	(39, 4, 'yes2', '2', 'HeroLichYes2.wav'),
	(39, 4, 'yes3', '3', 'HeroLichYes3.wav'),
	(39, 4, 'yes4', '4', 'HeroLichYes4.wav'),
	(39, 4, 'yes5', '5', 'HeroLichYes5.wav'),
	(39, 5, 'attack1', '1', 'HeroLichYesAttack1.wav'),
	(39, 5, 'attack2', '2', 'HeroLichYesAttack2.wav'),
	(39, 5, 'attack3', '3', 'HeroLichYesAttack3.wav'),
	(39, 6, 'fun1', '1', 'HeroLichPissed1.wav'),
	(39, 6, 'fun2', '2', 'HeroLichPissed2.wav'),
	(39, 6, 'fun3', '3', 'HeroLichPissed3.wav'),
	(39, 6, 'fun4', '4', 'HeroLichPissed4.wav'),
	(39, 6, 'fun5', '5', 'HeroLichPissed5.wav'),
	(39, 6, 'fun6', '6', 'HeroLichPissed6.wav'),
	(39, 6, 'fun7', '7', 'HeroLichPissed7.wav'),
	(39, 6, 'fun8', '8', 'HeroLichPissed8.wav'),
	(39, 7, 'death1', 'Mort', 'HeroLichDeath1.wav'),

	(40, 1, 'ready1', '1', 'HeroDreadlordReady1.wav'),
	(40, 2, 'warcry1', '1', 'HeroDreadlordWarcry1.wav'),
	(40, 3, 'what1', '1', 'HeroDreadlordWhat1.wav'),
	(40, 3, 'what2', '2', 'HeroDreadlordWhat2.wav'),
	(40, 3, 'what3', '3', 'HeroDreadlordWhat3.wav'),
	(40, 3, 'what4', '4', 'HeroDreadlordWhat4.wav'),
	(40, 4, 'yes1', '1', 'HeroDreadlordYes1.wav'),
	(40, 4, 'yes2', '2', 'HeroDreadlordYes2.wav'),
	(40, 4, 'yes3', '3', 'HeroDreadlordYes3.wav'),
	(40, 4, 'yes4', '4', 'HeroDreadlordYes4.wav'),
	(40, 5, 'attack1', '1', 'HeroDreadlordYesAttack1.wav'),
	(40, 5, 'attack2', '2', 'HeroDreadlordYesAttack2.wav'),
	(40, 5, 'attack3', '3', 'HeroDreadlordYesAttack3.wav'),
	(40, 6, 'fun1', '1', 'HeroDreadlordPissed1.wav'),
	(40, 6, 'fun2', '2', 'HeroDreadlordPissed2.wav'),
	(40, 6, 'fun3', '3', 'HeroDreadlordPissed3.wav'),
	(40, 6, 'fun4', '4', 'HeroDreadlordPissed4.wav'),
	(40, 6, 'fun5', '5', 'HeroDreadlordPissed5.wav'),
	(40, 6, 'fun6', '6', 'HeroDreadlordPissed6.wav'),
	(40, 6, 'fun7', '7', 'HeroDreadlordPissed7.wav'),

	(42, 1, 'ready1', '1', 'AcolyteReady1.wav'),
	(42, 2, 'warcry1', '1', 'AcolyteWarcry1.wav'),
	(42, 3, 'what1', '1', 'AcolyteWhat1.wav'),
	(42, 3, 'what2', '2', 'AcolyteWhat2.wav'),
	(42, 3, 'what3', '3', 'AcolyteWhat3.wav'),
	(42, 3, 'what4', '4', 'AcolyteWhat4.wav'),
	(42, 3, 'what5', '5', 'AcolyteWhat5.wav'),
	(42, 4, 'yes1', '1', 'AcolyteYes1.wav'),
	(42, 4, 'yes2', '2', 'AcolyteYes2.wav'),
	(42, 4, 'yes3', '3', 'AcolyteYes3.wav'),
	(42, 4, 'yes4', '4', 'AcolyteYes4.wav'),
	(42, 5, 'attack1', '1', 'AcolyteYesAttack1.wav'),
	(42, 5, 'attack2', '2', 'AcolyteYesAttack2.wav'),
	(42, 5, 'attack3', '3', 'AcolyteYesAttack3.wav'),
	(42, 6, 'fun1', '1', 'AcolytePissed1.wav'),
	(42, 6, 'fun2', '2', 'AcolytePissed2.wav'),
	(42, 6, 'fun3', '3', 'AcolytePissed3.wav'),
	(42, 6, 'fun4', '4', 'AcolytePissed4.wav'),
	(42, 6, 'fun5', '5', 'AcolytePissed5.wav'),
	(42, 6, 'fun6', '6', 'AcolytePissed6.wav'),
	(42, 6, 'fun7', '7', 'AcolytePissed7.wav'),
	(42, 6, 'fun8', '8', 'AcolytePissed8.wav'),
	(42, 7, 'death1', 'Mort', 'AcolyteDeath1.wav'),

	(43, 1, 'ready1', '1', 'GhoulReady1.wav'),
	(43, 2, 'warcry1', '1', 'GhoulWarcry1.wav'),
	(43, 3, 'what1', '1', 'GhoulWhat1.wav'),
	(43, 3, 'what2', '2', 'GhoulWhat2.wav'),
	(43, 3, 'what3', '3', 'GhoulWhat3.wav'),
	(43, 3, 'what4', '4', 'GhoulWhat4.wav'),
	(43, 4, 'yes1', '1', 'GhoulYes1.wav'),
	(43, 4, 'yes2', '2', 'GhoulYes2.wav'),
	(43, 4, 'yes3', '3', 'GhoulYes3.wav'),
	(43, 4, 'yes4', '4', 'GhoulYes4.wav'),
	(43, 5, 'attack1', '1', 'GhoulYesAttack1.wav'),
	(43, 5, 'attack2', '2', 'GhoulYesAttack2.wav'),
	(43, 5, 'attack3', '3', 'GhoulYesAttack3.wav'),
	(43, 5, 'attack4', '4', 'GhoulYesAttack4.wav'),
	(43, 6, 'fun1', '1', 'GhoulPissed1.wav'),
	(43, 6, 'fun2', '2', 'GhoulPissed2.wav'),
	(43, 6, 'fun3', '3', 'GhoulPissed3.wav'),
	(43, 6, 'fun4', '4', 'GhoulPissed4.wav'),
	(43, 7, 'death1', 'Mort', 'GhoulDeath.wav'),

	(44, 1, 'ready1', '1', 'CryptfiendReady1.wav'),
	(44, 2, 'warcry1', '1', 'CryptfiendWarcry1.wav'),
	(44, 3, 'what1', '1', 'CryptfiendWhat1.wav'),
	(44, 3, 'what2', '2', 'CryptfiendWhat2.wav'),
	(44, 3, 'what3', '3', 'CryptfiendWhat3.wav'),
	(44, 3, 'what4', '4', 'CryptfiendWhat4.wav'),
	(44, 4, 'yes1', '1', 'CryptfiendYes1.wav'),
	(44, 4, 'yes2', '2', 'CryptfiendYes2.wav'),
	(44, 4, 'yes3', '3', 'CryptfiendYes3.wav'),
	(44, 4, 'yes4', '4', 'CryptfiendYes4.wav'),
	(44, 5, 'attack1', '1', 'CryptfiendYesAttack1.wav'),
	(44, 5, 'attack2', '2', 'CryptfiendYesAttack2.wav'),
	(44, 5, 'attack3', '3', 'CryptfiendYesAttack3.wav'),
	(44, 6, 'fun1', '1', 'CryptfiendPissed1.wav'),
	(44, 6, 'fun2', '2', 'CryptfiendPissed2.wav'),
	(44, 6, 'fun3', '3', 'CryptfiendPissed3.wav'),
	(44, 6, 'fun4', '4', 'CryptfiendPissed4.wav'),
	(44, 6, 'fun5', '5', 'CryptfiendPissed5.wav'),
	(44, 6, 'fun6', '6', 'CryptfiendPissed6.wav'),
	(44, 6, 'fun7', '7', 'CryptfiendPissed7.wav'),

	(45, 1, 'ready1', 'J''obéis', 'AbominationReady1.wav'),
	(45, 2, 'warcry1', 'Tous pour un', 'AbominationWarcry1.wav'),
	(45, 3, 'what1', 'Que faire ?', 'AbominationWhat1.wav'),
	(45, 3, 'what2', 'Gné ?', 'AbominationWhat2.wav'),
	(45, 3, 'what3', 'Quels ordres ?', 'AbominationWhat3.wav'),
	(45, 3, 'what4', 'Mmmm', 'AbominationWhat4.wav'),
	(45, 4, 'yes1', 'Nous, aller', 'AbominationYes1.wav'),
	(45, 4, 'yes2', 'Beuha', 'AbominationYes2.wav'),
	(45, 4, 'yes3', 'Obéir', 'AbominationYes3.wav'),
	(45, 4, 'yes4', 'Heeuaargheuh !', 'AbominationYes4.wav'),
	(45, 4, 'yes5', 'Heeuaargh !', 'AbominationYes5.wav'),
	(45, 5, 'attack1', 'Tuer !', 'AbominationYesAttack1.wav'),
	(45, 5, 'attack2', 'Heeuaargh !', 'AbominationYesAttack2.wav'),
	(45, 5, 'attack3', 'Mangeeer...', 'AbominationYesAttack3.wav'),
	(45, 5, 'attack4', 'Déchireeer...', 'AbominationYesAttack4.wav'),
	(45, 6, 'fun1', '', 'AbominationPissed1.wav'),
	(45, 6, 'fun2', 'La mort vous va si bien', 'AbominationPissed2.wav'),
	(45, 6, 'fun3', 'Ne meurt que deux fois', 'AbominationPissed3.wav'),
	(45, 6, 'fun4', 'Voir la Légion et mourir', 'AbominationPissed4.wav'),
	(45, 6, 'fun5', 'Je suis trop jeune pour re-mourir', 'AbominationPissed5.wav'),
	(45, 6, 'fun6', 'Requiem pour un cou', 'AbominationPissed6.wav'),
	(45, 7, 'death1', 'Mort', 'AbominationAlternateDeath1.wav'),

	(46, 1, 'ready1', '1', 'NecromancerReady1.wav'),
	(46, 2, 'warcry1', '1', 'NecromancerWarcry1.wav'),
	(46, 3, 'what1', '1', 'NecromancerWhat1.wav'),
	(46, 3, 'what2', '2', 'NecromancerWhat2.wav'),
	(46, 3, 'what3', '3', 'NecromancerWhat3.wav'),
	(46, 3, 'what4', '4', 'NecromancerWhat4.wav'),
	(46, 4, 'yes1', '1', 'NecromancerYes1.wav'),
	(46, 4, 'yes2', '2', 'NecromancerYes2.wav'),
	(46, 4, 'yes3', '3', 'NecromancerYes3.wav'),
	(46, 4, 'yes4', '4', 'NecromancerYes4.wav'),
	(46, 5, 'attack1', '1', 'NecromancerYesAttack1.wav'),
	(46, 5, 'attack2', '2', 'NecromancerYesAttack2.wav'),
	(46, 5, 'attack3', '3', 'NecromancerYesAttack3.wav'),
	(46, 6, 'fun1', '1', 'NecromancerPissed1.wav'),
	(46, 6, 'fun2', '2', 'NecromancerPissed2.wav'),
	(46, 6, 'fun3', '3', 'NecromancerPissed3.wav'),
	(46, 6, 'fun4', '4', 'NecromancerPissed4.wav'),
	(46, 6, 'fun5', '5', 'NecromancerPissed5.wav'),
	(46, 7, 'death1', 'Mort', 'NecromancerDeath.wav'),

	(47, 1, 'ready1', '1', 'BansheeReady1.wav'),
	(47, 2, 'warcry1', '1', 'BansheeWarcry1.wav'),
	(47, 3, 'ghostwhat1', '1', 'BansheeGhostwhat1.wav'),
	(47, 3, 'what1', '1', 'BansheeWhat1.wav'),
	(47, 3, 'what2', '2', 'BansheeWhat2.wav'),
	(47, 3, 'what3', '3', 'BansheeWhat3.wav'),
	(47, 3, 'what4', '4', 'BansheeWhat4.wav'),
	(47, 3, 'what5', '5', 'BansheeWhat5.wav'),
	(47, 4, 'ghostyes1', '1', 'BansheeGhostyes1.wav'),
	(47, 4, 'ghostyes2', '2', 'BansheeGhostyes2.wav'),
	(47, 4, 'yes1', '1', 'BansheeYes1.wav'),
	(47, 4, 'yes2', '2', 'BansheeYes2.wav'),
	(47, 4, 'yes3', '3', 'BansheeYes3.wav'),
	(47, 4, 'yes4', '4', 'BansheeYes4.wav'),
	(47, 4, 'yes5', '5', 'BansheeYes5.wav'),
	(47, 5, 'attack1', '1', 'BansheeYesAttack1.wav'),
	(47, 5, 'attack2', '2', 'BansheeYesAttack2.wav'),
	(47, 5, 'attack3', '3', 'BansheeYesAttack3.wav'),
	(47, 5, 'ghostattack1', '1', 'BansheeYesAttack1.wav'),
	(47, 5, 'ghostattack2', '2', 'BansheeYesAttack2.wav'),
	(47, 6, 'fun1', '1', 'BansheePissed1.wav'),
	(47, 6, 'fun2', '2', 'BansheePissed2.wav'),
	(47, 6, 'fun3', '3', 'BansheePissed3.wav'),
	(47, 6, 'fun4', '4', 'BansheePissed4.wav'),
	(47, 6, 'fun5', '5', 'BansheePissed5.wav'),
	(47, 7, 'death1', 'Mort', 'BansheeDeath.wav'),
	(47, 7, 'ghostdeath1', '1', 'BansheeGhostdeath1.wav'),

	(48, 1, 'ready1', '1', 'ShadeReady1.wav'),
	(48, 2, 'warcry1', '1', 'ShadeWarcry1.wav'),
	(48, 3, 'what1', '1', 'ShadeWhat1.wav'),
	(48, 3, 'what2', '2', 'ShadeWhat2.wav'),
	(48, 3, 'what3', '3', 'ShadeWhat3.wav'),
	(48, 4, 'yes1', '1', 'ShadeYes1.wav'),
	(48, 4, 'yes2', '2', 'ShadeYes2.wav'),
	(48, 4, 'yes3', '3', 'ShadeYes3.wav'),
	(48, 4, 'yes4', '4', 'ShadeYes4.wav'),
	(48, 5, 'attack1', '1', 'ShadeYesAttack1.wav'),
	(48, 5, 'attack2', '2', 'ShadeYesAttack2.wav'),
	(48, 5, 'attack3', '3', 'ShadeYesAttack3.wav'),
	(48, 5, 'attack4', '4', 'ShadeYesAttack4.wav'),
	(48, 5, 'attack5', '5', 'ShadeYesAttack5.wav'),
	(48, 6, 'fun1', '1', 'ShadePissed1.wav'),
	(48, 6, 'fun2', '2', 'ShadePissed2.wav'),
	(48, 6, 'fun3', '3', 'ShadePissed3.wav'),
	(48, 6, 'fun4', '4', 'ShadePissed4.wav'),
	(48, 6, 'fun5', '5', 'ShadePissed5.wav'),
	(48, 6, 'fun6', '6', 'ShadePissed6.wav'),
	(48, 7, 'death1', 'Mort', 'ShadeDeath1.wav'),

	(57, 2, 'warcry1', '1', 'ArthasWarcry1.wav'),
	(57, 3, 'what1', '1', 'ArthasWhat1.wav'),
	(57, 3, 'what2', '2', 'ArthasWhat2.wav'),
	(57, 3, 'what3', '3', 'ArthasWhat3.wav'),
	(57, 3, 'what4', '4', 'ArthasWhat4.wav'),
	(57, 3, 'what5', '5', 'ArthasWhat5.wav'),
	(57, 4, 'yes1', '1', 'ArthasYes1.wav'),
	(57, 4, 'yes2', '2', 'ArthasYes2.wav'),
	(57, 4, 'yes3', '3', 'ArthasYes3.wav'),
	(57, 4, 'yes4', '4', 'ArthasYes4.wav'),
	(57, 5, 'attack1', '1', 'ArthasYesAttack1.wav'),
	(57, 5, 'attack2', '2', 'ArthasYesAttack2.wav'),
	(57, 5, 'attack3', '3', 'ArthasYesAttack3.wav'),
	(57, 5, 'attack4', '4', 'ArthasYesAttack4.wav'),
	(57, 5, 'attack5', '5', 'ArthasYesAttack5.wav'),
	(57, 5, 'attack6', '6', 'ArthasYesAttack6.wav'),
	(57, 6, 'fun1', '1', 'ArthasPissed1.wav'),
	(57, 6, 'fun2', '2', 'ArthasPissed2.wav'),
	(57, 6, 'fun3', '3', 'ArthasPissed3.wav'),
	(57, 6, 'fun4', '4', 'ArthasPissed4.wav'),
	(57, 6, 'fun5', '5', 'ArthasPissed5.wav'),
	(57, 6, 'fun6', '6', 'ArthasPissed6.wav'),
	(57, 6, 'fun7', '7', 'ArthasPissed7.wav'),

	(83, 2, 'warcry1', '1', 'KelthuzadWarcry1.wav'),
	(83, 3, 'what1', '1', 'KelthuzadWhat1.wav'),
	(83, 3, 'what2', '2', 'KelthuzadWhat2.wav'),
	(83, 3, 'what3', '3', 'KelthuzadWhat3.wav'),
	(83, 3, 'what4', '4', 'KelthuzadWhat4.wav'),
	(83, 4, 'yes1', '1', 'KelthuzadYes1.wav'),
	(83, 4, 'yes2', '2', 'KelthuzadYes2.wav'),
	(83, 4, 'yes3', '3', 'KelthuzadYes3.wav'),
	(83, 4, 'yes4', '4', 'KelthuzadYes4.wav'),
	(83, 5, 'attack1', '1', 'KelthuzadYesAttack1.wav'),
	(83, 5, 'attack2', '2', 'KelthuzadYesAttack2.wav'),
	(83, 5, 'attack3', '3', 'KelthuzadYesAttack3.wav'),
	(83, 6, 'fun1', '1', 'KelthuzadPissed1.wav'),
	(83, 6, 'fun2', '2', 'KelthuzadPissed2.wav'),
	(83, 6, 'fun3', '3', 'KelthuzadPissed3.wav'),
	(83, 6, 'fun4', '4', 'KelthuzadPissed4.wav'),
	(83, 6, 'fun5', '5', 'KelthuzadPissed5.wav'),
	(83, 7, 'death1', '1', 'kelthuzadDeath1.mp3'),

	(85, 2, 'warcry1', '1', 'TichondriusWarcry1.wav'),
	(85, 3, 'what1', '1', 'TichondriusWhat1.wav'),
	(85, 3, 'what2', '2', 'TichondriusWhat2.wav'),
	(85, 3, 'what3', '3', 'TichondriusWhat3.wav'),
	(85, 3, 'what4', '4', 'TichondriusWhat4.wav'),
	(85, 4, 'yes1', '1', 'TichondriusYes1.wav'),
	(85, 4, 'yes2', '2', 'TichondriusYes2.wav'),
	(85, 4, 'yes3', '3', 'TichondriusYes3.wav'),
	(85, 4, 'yes4', '4', 'TichondriusYes4.wav'),
	(85, 5, 'attack1', '1', 'TichondriusYesAttack1.wav'),
	(85, 5, 'attack2', '2', 'TichondriusYesAttack2.wav'),
	(85, 5, 'attack3', '3', 'TichondriusYesAttack3.wav'),
	(85, 6, 'fun1', '1', 'TichondriusPissed1.wav'),
	(85, 6, 'fun2', '2', 'TichondriusPissed2.wav'),
	(85, 6, 'fun3', '3', 'TichondriusPissed3.wav'),
	(85, 6, 'fun4', '4', 'TichondriusPissed4.wav'),
	(85, 6, 'fun5', '5', 'TichondriusPissed5.wav'),

	-- neutrals

	(55, 3, 'what1', '1', 'PitlordWhat1.wav'),
	(55, 3, 'what2', '2', 'PitlordWhat2.wav'),
	(55, 3, 'what3', '3', 'PitlordWhat3.wav'),
	(55, 4, 'yes1', '1', 'PitlordYes1.wav'),
	(55, 4, 'yes2', '2', 'PitlordYes2.wav'),
	(55, 4, 'yes3', '3', 'PitlordYes3.wav'),
	(55, 5, 'attack1', '1', 'PitlordYesAttack1.wav'),
	(55, 5, 'attack2', '2', 'PitlordYesAttack2.wav'),
	(55, 5, 'attack3', '3', 'PitlordYesAttack3.wav'),

	(58, 2, 'warcry1', '1', 'BanditWarcry1.wav'),
	(58, 3, 'what1', '1', 'BanditWhat1.wav'),
	(58, 3, 'what2', '2', 'BanditWhat2.wav'),
	(58, 3, 'what3', '3', 'BanditWhat3.wav'),
	(58, 4, 'yes1', '1', 'BanditYes1.wav'),
	(58, 4, 'yes2', '2', 'BanditYes2.wav'),
	(58, 4, 'yes3', '3', 'BanditYes3.wav'),
	(58, 5, 'attack1', '1', 'BanditYesAttack1.wav'),
	(58, 5, 'attack2', '2', 'BanditYesAttack2.wav'),
	(58, 5, 'attack3', '3', 'BanditYesAttack3.wav'),
	(58, 6, 'fun1', '1', 'BanditPissed1.wav'),
	(58, 6, 'fun2', '2', 'BanditPissed2.wav'),
	(58, 6, 'fun3', '3', 'BanditPissed3.wav'),
	(58, 6, 'fun4', '4', 'BanditPissed4.wav'),
	(58, 6, 'fun5', '5', 'BanditPissed5.wav'),
	(58, 7, 'death1', 'Mort', 'BanditDeath1.wav'),
	
	(66, 1, 'ready1', '1', 'ForesttrollReady1.wav'),
	(66, 2, 'warcry1', '1', 'ForesttrollWarcry1.wav'),
	(66, 3, 'what1', '1', 'ForesttrollWhat1.wav'),
	(66, 3, 'what2', '2', 'ForesttrollWhat2.wav'),
	(66, 3, 'what3', '3', 'ForesttrollWhat3.wav'),
	(66, 3, 'what4', '4', 'ForesttrollWhat4.wav'),
	(66, 4, 'yes1', '1', 'ForesttrollYes1.wav'),
	(66, 4, 'yes2', '2', 'ForesttrollYes2.wav'),
	(66, 4, 'yes3', '3', 'ForesttrollYes3.wav'),
	(66, 4, 'yes4', '4', 'ForesttrollYes4.wav'),
	(66, 5, 'attack1', '1', 'ForesttrollYesAttack1.wav'),
	(66, 5, 'attack2', '2', 'ForesttrollYesAttack2.wav'),
	(66, 5, 'attack3', '3', 'ForesttrollYesAttack3.wav'),
	(66, 5, 'attack4', '4', 'ForesttrollYesAttack4.wav'),
	(66, 6, 'fun1', '1', 'ForesttrollPissed1.wav'),
	(66, 6, 'fun2', '2', 'ForesttrollPissed2.wav'),
	(66, 6, 'fun3', '3', 'ForesttrollPissed3.wav'),
	(66, 6, 'fun4', '4', 'ForesttrollPissed4.wav'),
	(66, 6, 'fun5', '5', 'ForesttrollPissed5.wav'),
	(66, 6, 'fun6', '6', 'ForesttrollPissed6.wav'),
	(66, 7, 'death1', '1', 'ForesttrollDeath.wav'),

	(67, 3, 'what1', '1', 'GoblinmerchantWhat1.wav'),
	(67, 3, 'what2', '2', 'GoblinmerchantWhat2.wav'),
	(67, 3, 'what3', '3', 'GoblinmerchantWhat3.wav'),

	(68, 1, 'ready1', '1', 'GoblinsapperReady1.wav'),
	(68, 2, 'warcry1', '1', 'GoblinsapperWarcry1.wav'),
	(68, 3, 'what1', '1', 'GoblinsapperWhat1.wav'),
	(68, 3, 'what2', '2', 'GoblinsapperWhat2.wav'),
	(68, 3, 'what3', '3', 'GoblinsapperWhat3.wav'),
	(68, 3, 'what4', '4', 'GoblinsapperWhat4.wav'),
	(68, 3, 'what5', '5', 'GoblinsapperWhat5.wav'),
	(68, 4, 'yes1', '1', 'GoblinsapperYes1.wav'),
	(68, 4, 'yes2', '2', 'GoblinsapperYes2.wav'),
	(68, 4, 'yes3', '3', 'GoblinsapperYes3.wav'),
	(68, 4, 'yes4', '4', 'GoblinsapperYes4.wav'),
	(68, 4, 'yes5', '5', 'GoblinsapperYes5.wav'),
	(68, 5, 'attack1', '1', 'GoblinsapperYesAttack1.wav'),
	(68, 5, 'attack2', '2', 'GoblinsapperYesAttack2.wav'),
	(68, 5, 'attack3', '3', 'GoblinsapperYesAttack3.wav'),
	(68, 5, 'attack4', '4', 'GoblinsapperYesAttack4.wav'),
	(68, 5, 'attack5', '5', 'GoblinsapperYesAttack5.wav'),
	(68, 6, 'fun1', '1', 'GoblinsapperPissed1.wav'),
	(68, 6, 'fun2', '2', 'GoblinsapperPissed2.wav'),
	(68, 6, 'fun3', '3', 'GoblinsapperPissed3.wav'),
	(68, 6, 'fun4', '4', 'GoblinsapperPissed4.wav'),
	(68, 6, 'fun5', '5', 'GoblinsapperPissed5.wav'),
	(68, 6, 'fun6', '6', 'GoblinsapperPissed6.wav'),
	(68, 6, 'fun7', '7', 'GoblinsapperPissed7.wav'),
	(68, 7, 'death1', '1', 'GoblinsapperDeath1.wav'),

	(69, 1, 'ready1', '1', 'GoblinzeppelinReady1.wav'),
	(69, 3, 'what1', '1', 'GoblinzeppelinWhat1.wav'),
	(69, 3, 'what2', '2', 'GoblinzeppelinWhat2.wav'),
	(69, 3, 'what3', '3', 'GoblinzeppelinWhat3.wav'),
	(69, 3, 'what4', '4', 'GoblinzeppelinWhat4.wav'),
	(69, 4, 'yes1', '1', 'GoblinzeppelinYes1.wav'),
	(69, 4, 'yes2', '2', 'GoblinzeppelinYes2.wav'),
	(69, 4, 'yes3', '3', 'GoblinzeppelinYes3.wav'),
	(69, 4, 'yes4', '4', 'GoblinzeppelinYes4.wav'),
	(69, 6, 'fun1', '1', 'GoblinzeppelinPissed1.wav'),
	(69, 6, 'fun2', '2', 'GoblinzeppelinPissed2.wav'),
	(69, 6, 'fun3', '3', 'GoblinzeppelinPissed3.wav'),
	(69, 6, 'fun4', '4', 'GoblinzeppelinPissed4.wav'),
	(69, 6, 'fun5', '5', 'GoblinzeppelinPissed5.wav'),
	(69, 6, 'fun6', '6', 'GoblinzeppelinPissed6.wav'),
	(69, 7, 'death1', '1', 'GoblinzeppelinDeath1.wav'),

	(70, 1, 'ready1', '1', 'IcetrollReady1.wav'),
	(70, 2, 'warcry1', '1', 'IcetrollWarcry1.wav'),
	(70, 3, 'what1', '1', 'IcetrollWhat1.wav'),
	(70, 3, 'what2', '2', 'IcetrollWhat2.wav'),
	(70, 3, 'what3', '3', 'IcetrollWhat3.wav'),
	(70, 3, 'what4', '4', 'IcetrollWhat4.wav'),
	(70, 3, 'what5', '5', 'IcetrollWhat5.wav'),
	(70, 4, 'yes1', '1', 'IcetrollYes1.wav'),
	(70, 4, 'yes2', '2', 'IcetrollYes2.wav'),
	(70, 4, 'yes3', '3', 'IcetrollYes3.wav'),
	(70, 4, 'yes4', '4', 'IcetrollYes4.wav'),
	(70, 4, 'yes5', '5', 'IcetrollYes5.wav'),
	(70, 5, 'attack1', '1', 'IcetrollYesAttack1.wav'),
	(70, 5, 'attack2', '2', 'IcetrollYesAttack2.wav'),
	(70, 6, 'fun1', '1', 'IcetrollPissed1.wav'),
	(70, 6, 'fun2', '2', 'IcetrollPissed2.wav'),
	(70, 6, 'fun3', '3', 'IcetrollPissed3.wav'),
	(70, 6, 'fun4', '4', 'IcetrollPissed4.wav'),
	(70, 7, 'death1', '1', 'IcetrollDeath.wav'),

	(71, 1, 'ready1', '1', 'OgreReady1.wav'),
	(71, 2, 'warcry1', '1', 'OgreWarcry1.wav'),
	(71, 3, 'what1', '1', 'OgreWhat1.wav'),
	(71, 3, 'what2', '2', 'OgreWhat2.wav'),
	(71, 3, 'what3', '3', 'OgreWhat3.wav'),
	(71, 3, 'what4', '4', 'OgreWhat4.wav'),
	(71, 4, 'yes1', '1', 'OgreYes1.wav'),
	(71, 4, 'yes2', '2', 'OgreYes2.wav'),
	(71, 4, 'yes3', '3', 'OgreYes3.wav'),
	(71, 4, 'yes4', '4', 'OgreYes4.wav'),
	(71, 5, 'attack1', '1', 'OgreYesAttack1.wav'),
	(71, 5, 'attack2', '2', 'OgreYesAttack2.wav'),
	(71, 5, 'attack3', '3', 'OgreYesAttack3.wav'),
	(71, 6, 'fun1', '1', 'OgrePissed1.wav'),
	(71, 6, 'fun2', '2', 'OgrePissed2.wav'),
	(71, 6, 'fun3', '3', 'OgrePissed3.wav'),
	(71, 6, 'fun4', '4', 'OgrePissed4.wav'),
	(71, 6, 'fun5', '5', 'OgrePissed5.wav'),
	(71, 7, 'death1', '1', 'OgreDeath1.wav'),

	(72, 1, 'ready1', '1', 'SatyreReady1.wav'),
	(72, 2, 'warcry1', '1', 'SatyreWarcry1.wav'),
	(72, 3, 'what1', '1', 'SatyreWhat1.wav'),
	(72, 3, 'what2', '2', 'SatyreWhat2.wav'),
	(72, 3, 'what3', '3', 'SatyreWhat3.wav'),
	(72, 4, 'yes1', '1', 'SatyreYes1.wav'),
	(72, 4, 'yes2', '2', 'SatyreYes2.wav'),
	(72, 4, 'yes3', '3', 'SatyreYes3.wav'),
	(72, 4, 'yes4', '4', 'SatyreYes4.wav'),
	(72, 5, 'attack1', '1', 'SatyreYesAttack1.wav'),
	(72, 5, 'attack2', '2', 'SatyreYesAttack2.wav'),
	(72, 5, 'attack3', '3', 'SatyreYesAttack3.wav'),
	(72, 6, 'fun1', '1', 'SatyrePissed1.wav'),
	(72, 6, 'fun2', '2', 'SatyrePissed2.wav'),
	(72, 6, 'fun3', '3', 'SatyrePissed3.wav'),
	(72, 6, 'fun4', '4', 'SatyrePissed4.wav'),
	(72, 6, 'fun5', '5', 'SatyrePissed5.wav');
