CREATE TABLE races (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	code VARCHAR(20) NOT NULL,
	name VARCHAR(25) NOT NULL,
	UNIQUE (code)
);

INSERT INTO races (id, code, name) VALUES
(1, 'humans', 'Humains'),
(2, 'nightelfs', 'Elfes de la nuit'),
(3, 'orcs', 'Orcs'),
(4, 'undeads', 'Morts vivants'),
(5, 'neutrals', 'Neutres');

CREATE TABLE characters (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  k_race INTEGER NOT NULL,
  code varchar(20) NOT NULL,
  name varchar(25) NOT NULL,
  tft tinyint(1) NOT NULL DEFAULT 0,
  UNIQUE (k_race, code),
  FOREIGN KEY (k_race) REFERENCES races (id) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO characters (id, k_race, code, name, tft) VALUES
(1, 1, 'paladin', 'Paladin', 0),
(2, 1, 'mountainking', 'Roi de la montagne', 0),
(3, 1, 'archmage', 'Archimage', 0),
(4, 1, 'bloodelfmage', 'Mage elfe de sang', 1),
(5, 1, 'peasant', 'Paysan', 0),
(6, 1, 'footman', 'Soldat', 0),
(7, 1, 'rifleman', 'Fusiller', 0),
(8, 1, 'knight', 'Chevalier', 0),
(9, 1, 'gyrocopter', 'Gyrocoptère', 0),
(10, 1, 'gryphonrider', 'Chevaucheur de gryphon', 0),
(11, 1, 'priest', 'Prêtre', 0),
(12, 1, 'sorceress', 'Sorcière', 0),
(13, 1, 'spellbreaker', 'spellbreaker', 1),
(14, 1, 'hawkrider', 'hawkrider', 1),
(15, 3, 'blademaster', 'blademaster', 0),
(16, 3, 'farseer', 'farseer', 0),
(17, 3, 'taurenchieftain', 'taurenchieftain', 0),
(18, 3, 'shadowhunter', 'shadowhunter', 1),
(19, 3, 'peon', 'peon', 0),
(20, 3, 'grunt', 'grunt', 0),
(21, 3, 'headhunter', 'headhunter', 0),
(22, 3, 'wolfrider', 'wolfrider', 0),
(23, 3, 'wyvernrider', 'wyvernrider', 0),
(24, 3, 'tauren', 'tauren', 0),
(25, 3, 'shaman', 'shaman', 0),
(26, 3, 'witchdoctor', 'witchdoctor', 0),
(27, 3, 'spiritwalker', 'spiritwalker', 1),
(28, 2, 'demonhunter', 'Chasseur de démons', 0),
(29, 2, 'keeperofthegrove', 'keeperofthegrove', 0),
(30, 2, 'moonpriestess', 'Prêtresse de la lune', 0),
(31, 2, 'warden', 'warden', 1),
(32, 2, 'archer', 'Archer', 0),
(33, 2, 'huntress', 'Chasseresse', 0),
(34, 2, 'dryad', 'Dryade', 0),
(35, 2, 'druidoftheclaw', 'druidoftheclaw', 0),
(36, 2, 'druidofthetalon', 'druidofthetalon', 0),
(37, 2, 'hippogryphrider', 'Chevaucheur d''hippogryphe', 0),
(38, 4, 'deathknight', 'Chevalier de la mort', 0),
(39, 4, 'lich', 'Liche', 0),
(40, 4, 'dreadlord', 'dreadlord', 0),
(41, 4, 'cryptlord', 'cryptlord', 1),
(42, 4, 'acolyte', 'Acolyte', 0),
(43, 4, 'ghoul', 'Goule', 0),
(44, 4, 'cryptfiend', 'cryptfiend', 0),
(45, 4, 'abomination', 'Abomination', 0),
(46, 4, 'necromancer', 'Nécromancien', 0),
(47, 4, 'banshee', 'Banshee', 0),
(48, 4, 'shade', 'Ombre', 0),
(49, 5, 'alchemist', 'alchemist', 1),
(50, 5, 'ladyvash', 'ladyvash', 1),
(51, 5, 'tinker', 'tinker', 1),
(52, 5, 'beastmaster', 'beastmaster', 1),
(53, 5, 'pandaren', 'pandaren', 1),
(54, 5, 'darkranger', 'darkranger', 1),
(55, 5, 'pitlord', 'pitlord', 0),
(56, 5, 'firelord', 'firelord', 1),
(57, 4, 'arthas', 'Arthas', 0),
(58, 5, 'bandit', 'Bandit', 0),
(59, 1, 'jaina', 'Jaina', 0),
(60, 1, 'mortarteam', 'Mortier', 0),
(61, 1, 'muradin', 'Muradin', 0),
(62, 1, 'uther', 'Uther', 0),
(63, 1, 'windserpent', 'windserpent', 0),
(64, 1, 'villager', 'Villageois', 0),
(65, 1, 'captain', 'Capitaine', 0),
(66, 5, 'foresttroll', 'foresttroll', 0),
(67, 5, 'goblinmerchant', 'goblinmerchant', 0),
(68, 5, 'goblinsapper', 'goblinsapper', 0),
(69, 5, 'goblinzeppelin', 'goblinzeppelin', 0),
(70, 5, 'icetroll', 'icetroll', 0),
(71, 5, 'ogre', 'ogre', 0),
(72, 5, 'satyre', 'satyre', 0),
(73, 2, 'furion', 'Furion', 0),
(74, 2, 'illidan', 'Illidan', 0),
(75, 2, 'illidanmorphed', 'Illidan transformé', 0),
(76, 2, 'shandris', 'Shandris', 0),
(77, 2, 'sylvanas', 'Sylvanas', 0),
(78, 2, 'tyrande', 'Tyrande', 0),
(79, 3, 'cairne', 'Cairne', 0),
(80, 3, 'grom', 'Grom', 0),
(81, 3, 'thrall', 'Thrall', 0),
(82, 3, 'warlord', 'Warlord', 0),
(83, 4, 'kelthuzad', 'Kelthuzad', 0),
(85, 4, 'tichondrius', 'Tichondrius', 0);
